---
sidebar: sidebar 
permalink: nkfsosm_kfs_billing.html 
keywords: netapp, keystone, billing, Keystone billing logic, charges, charging, billing cycle, billing schedule, MetroCluster billing, TMP temporary volumes, Adaptive QoS policy billing, cloned volumes, burst billing 
summary: Keystone 帳單 
---
= Keystone 帳單
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
支援可預測且預先定價的儲存訂閱方案。NetApp Keystone

如果您偏好營運支出（營運支出）消費模式、而非資本支出（資本支出）或租賃模式、您可以選擇Keystone隨成長付費模式、以因應靈活且可擴充的消費需求。

Keystone提供您下列帳單管理功能：

* 您可以根據 IOPS 和延遲承諾容量來支付費用、以滿足各種工作負載需求。不同的效能服務層級（ Extreme 、 Premium 、 Standard 及 Value ）可讓您根據 Keystone 服務所購買的服務層級來管理儲存設備。
* 它提供可預測的計費方式、可針對已提交的容量、以及針對可變（突發）容量使用量的「依使用量付費」。
* 您可以針對硬體、核心作業系統及支援選擇套裝組合價格、只需支付一美元 / TiB 的價格。每種儲存類型、檔案、區塊、物件或雲端儲存服務都有一張發票。
* 選擇靈活的服務條款與付款條件：您可以選擇每個站台 12 個月、 100TiB 或更多。之後、您可以自動續約 12 個月或每月續約。


Keystone計費是根據已提交的容量和可變的突發消耗量來計算。

如需已認可及突發容量使用量的相關資訊、請參閱 link:nkfsosm_keystone_service_capacity_definitions.html["Keystone 服務容量定義"]。



== 根據已提交的容量進行計費

承諾容量是指各方（ NetApp / 合作夥伴和客戶）在單一訂閱中議定的各種服務容量。此容量會在每個Keystone訂單上註明、而且會計費、無論實際使用量為何。

.耗用容量的計量
作爲Keystone服務部署的一部分，NetApp會持續監控和衡量服務的使用量。每五分鐘至少一次、系統會產生一筆使用記錄、詳述訂閱目前的使用容量。這些記錄會在計費期間內彙總、以產生發票和使用報告。



== 根據尖峰使用量進行計費

當耗用容量大於指定服務層級的已認可容量時、系統會記錄突發消耗、並據此套用費用。產生的每個使用記錄都會執行此程序。因此、「暴增使用量」反映出您的過度使用容量在承諾容量之外的數量和使用期限。



== 帳單排程

Keystone 服務每月及每年收費。

.每月帳單
發票每月寄出一次。在下一個月內、系統會寄送一張發票給您提供服務的月份。例如、您在一月份使用的服務發票會在二月初寄送。此發票包含已確認容量的費用、以及任何突發使用量（若適用）。

.每年計費
每個訂購年度開始時、系統會產生一張發票、以支付已確認容量的最低付款額。它會在訂閱開始日期產生。另一張發票會在訂閱季度結束時寄出、並將該季任何突發使用量的適用費用加總。如果已提交的容量在訂閱期間有所變更、則會在承諾容量變更生效的同一天、針對該訂閱年其餘時間按比例支付的最低付款額、寄送發票。

.整月帳單的寬限期
在訂閱啟動的前 60 天內、您累積的任何突發使用量都會記錄下來、但不會在 Keystone 服務發票上收取費用。此寬限期可讓您將儲存設備設定成適當的調適性服務品質（AQO）設定、以便適當監控及計費。正確設定儲存設備時、您可以避免發生任何非預期的暴增費用。在60天的初始寬限期之後累積的任何突發使用量、都會在下一張發票上支付。此寬限期不會影響您現有訂閱的任何修改或續約。



== Keystone計費的其他案例

Keystone計費有幾種案例、您應該熟悉這些案例。



=== 複製磁碟區的收費

如果將磁碟區複製到 ONTAP 支援區中、並將其用於備份及還原資料、您可以繼續使用複本、而無需支付任何額外費用。然而、貴企業長期用於任何其他用途的複製磁碟區則需支付費用。

請注意下列事項：

* 只要實體磁碟區的大小低於父磁碟區的 10% 、就不需要充電（與父磁碟區中使用的實體容量相比、複製磁碟區中使用的實體容量）。
* 複製的磁碟區沒有 24 小時寬限期、只會考慮複製的大小。
* 一旦複製磁碟區超過父磁碟區實體大小的 10% 、複製就會以標準磁碟區（邏輯使用容量）計費。




=== 帳單 MetroCluster for 本

進階資料保護功能使用 NetApp MetroCluster 功能、在兩個實體分隔的叢集之間鏡射資料。在鏡射式集合體上 MetroCluster 、資料會在每個叢集上寫入兩次。每一側的基礎概念服務使用費、會產生兩筆相同的使用記錄。如果您透過 ONTAP 系統管理員（系統管理員）或 Active IQ Unified Manager （ Unified Manager ）監控叢集、您可能會發現這些工具和 Keystone 服務所報告的使用量差異。System Manager和Unified Manager不會在鏡射（遠端）叢集上報告磁碟區、因此會報告Keystone服務報告的使用量數據一半。

例如：站台 A 和站台 B 是 MetroCluster 以整套組態設定。當使用者在站台 A 中建立 10TB 的磁碟區時、站台 B 會建立相同的 10TB 磁碟區Keystone 可區分每個站台的磁碟區和記錄額外的 10TB 使用量、總容量增加 20TB 。System Manager 和 Unified Manager 報告在站台 A 中建立 10TB 磁碟區



=== 暫用磁碟區收費

有時 ONTAP 、當搬移 Volume 時、會由現象開發出暫用（ TMP ） Volume 。這些暫存磁碟區的壽命很短、而且不會測量這些磁碟區的使用量以供計費。



=== 計費和調適性 QoS 原則

Keystone 會根據服務層級來測量使用量。每個服務層級都與特定的調適性服務品質（QoS）原則相關聯。在部署期間、系統會通知您訂閱的Keystone服務的每個QoS原則詳細資料。在儲存管理作業期間、請確定您的磁碟區已根據訂閱的服務層級指派適當的QoS原則、以避免發生非預期的計費。如需 ONTAP 更多有關 QoS 原則的資訊、請參閱 link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["透過 QoS 總覽來保證處理量"]。



=== SnapMirror 目的地收費

SnapMirror目的地Volume的定價受來源所指派服務層級的QoS原則所規範。但是、如果來源沒有相關聯的 QoS 原則、則會根據可用的最低服務層級來計費目的地。



=== FlexGroups 計費

FlexGroups 是根據 FlexGroup 功能隨需調整的 QoS 原則來收費的。不考慮其成員的 QoS 原則。



=== LUN 計費

對於 LUN 、通常會遵循與 QoS 原則所管理的磁碟區相同的計費模式。如果在 LUN 上設定個別的 QoS 原則、則：

* LUN 的大小會根據該 LUN 的相關服務層級來計算、以供使用。
* 磁碟區中剩餘空間（如果有）會根據在磁碟區上設定之服務層級的 QoS 原則來收費。




=== 不需付費即可使用FabricPool

如果資料是從Keystone系統分層到ONTAP 不只是單純儲存服務（S3）物件儲存或NetApp StorageGRID 支援、則熱層（Keystone系統）的耗用容量將會減少分層的資料量、進而影響計費結果。無論ONTAP 您的需求StorageGRID 是由Keystone訂閱涵蓋的不只是S3儲存設備或是一套系統。

若要將資料分層至任何第三方物件儲存設備、請聯絡Keystone成功管理程式。

如需FabricPool 有關使用資訊技術進行Keystone訂閱的資訊、請參閱 link:nkfsosm_tiering.html["分層"]。



=== 系統與根磁碟區的收費

系統和根磁碟區會在Keystone服務的整體監控中受到監控、但不會計入或計費。這些磁碟區的使用量可免除計費。
