---
sidebar: sidebar 
permalink: nkfsosm_performance.html 
keywords: netapp, keystone, performance, service levels 
summary: Keystone 效能服務層級 
---
= 服務層級
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone 提供預先定義的效能服務層級容量（服務層級）。

每個服務層級都是由其I/O密度所定義、即效能（每秒輸入/輸出作業次數[IOP]）與已使用儲存設備（儲存資料的TiB）的比率、即IOPS/TiB。

由Keystone服務管理的每個Volume都與服務層級相關聯。所有 I/O 作業和在個別磁碟區上使用的所有儲存設備、都會納入磁碟區的 I/O 密度計算。

下表定義服務層級。



== 不同儲存類型的服務層級

此處列出檔案、區塊和物件儲存設備的服務層級。

報告磁碟區層級的 I/O 密度計算、以顯示上週的尖峰 I/O 密度。尖峰效能取決於每小時的時間間隔。每個磁碟區的 I/O 密度報告會每月產生一次、以衡量各服務層級的遵循程度。



=== 檔案服務

* 支援的傳輸協定 * ： NFS 、 CIFS 、 iSCSI 及 FC

|===


| * 服務層級 * | * 極致 * | * 優質 * | * 標準 * | * 價值 * 


| * 工作負載類型 * | 分析、資料庫 | VDI 、虛擬化應用程式、軟體開發 | 檔案共用、 Web 伺服器 | 備份 


| * 目標 IOPS/TiB* | 6 、 144 | 2 、 048 | 128/128 | 不適用 


| * 最大 IOPS / TiB* | 12288/3 | 4 、 096 | 512 | 不適用 


| * 最大處理量 MBps （ 32kb/IOP ） * | 384.. | 128/128 | 16 | 不適用 


| * 延遲 * | 不到 1 毫秒 | 低於 2 毫秒 | 低於 17 毫秒 | 不適用 


.2+| * 最小容量 * 、 1 、 2^ 4+| 100 TiB^1^ 


| 15 TiB^2^ | 25 TiB^2^ | 50 TiB^2^ | 50 TiB^2^ 
|===

NOTE: 最短一年期限和最小100TiB容量、適用於任何檔案共用和區塊服務層級的NetApp直接商機組合。^2^ 針對通路商機所選的每個服務層、最低一年期限和最低指定容量。



=== 區塊儲存

* 支援的傳輸協定 * ： FC 與 iSCSI

|===


| * 服務層級 * | * 極致 * | * 優質 * | * 標準 * 


| * 工作負載類型 * | 高效能運算 | 視訊監控 | 備份 


| * 目標 IOPS/TiB* 3+| 不適用 


| * 最大 IOPS / TiB* | 5.500 | 4 、 000 | 不適用 


| * 最大處理量 MBps （ 32kb/IOP ） * | 43. | 31 | 不適用 


| * 延遲 * | 低於 0.5 毫秒 | 低於 0.5 毫秒 | 不適用 


| * 最小容量 * 、 1 、 2^ | 100 TiB^3^ | 100 TiB^3^ | 300 TiB^3^ 
|===

NOTE: 最短一年期限和最小100TiB容量、適用於任何檔案共用和區塊服務層級的NetApp直接商機組合。^2^ 針對通路商機所選的每個服務層最低一年期限和最低指定容量。^3^ 針對任一商機類型所選取的每個服務層最低一年期限和最低指定容量。



=== 物件儲存

* 支援的傳輸協定 * ： S3

|===


| * 服務層級 * | 物件 


| * 工作負載類型 * | 媒體儲存庫、歸檔 


| * 目標 IOPS/TiB* | 不適用 


| * 最大 IOPS / TiB* | 不適用 


| * 最大處理量 MBps （ 32kb/IOP ） * | 不適用 


| * 延遲 * | 不適用 


| * 最小容量 * 、 1 、 2^ | 500 TiB^3^ 
|===

NOTE: 最短一年期限和最小100TiB容量、適用於任何檔案共用和區塊服務層級的NetApp直接商機組合。^2^ 針對通路商機所選的每個服務層最低一年期限和最低指定容量。^3^ 針對任一商機類型所選取的每個服務層最低一年期限和最低指定容量。

您可以從NetApp服務引擎使用者介面的多個畫面、將服務層級指派給您的訂閱。如需詳細資訊、請參閱 link:nkfsosm_tenancy_overview.html["Keystone 中的租賃和多租戶"]。
