---
sidebar: sidebar 
permalink: nkfsfaq_overview.html 
keywords: netapp, keystone, overview, 
summary: 概述 NetApp Keystone 
---
= 常見問題集（FAQ）NetApp Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
下列問題可回答您經常提出 NetApp Keystone 的有關解決方法的問題。

* NetApp Keystone 什麼是呢？*

NetApp Keystone 是內部部署資本支出（資本支出）替代方案的組合。如需詳細資訊、請參閱 https://["NetApp Keystone"]。

*此功能如何讓我的客戶受益？NetApp Keystone *

這個橋樑連接了資本支出和混合雲策略的支柱、提供敏捷度、財務靈活度及降低財務風險、協助客戶滿足現金流和業務需求。 NetApp Keystone

NetApp Keystone 品牌提供靈活的付款解決方案組合、包括傳統融資、租賃及固定 / 可變選項、適合注重現金的客戶、以及 Keystone 服務。

* Keystone 服務（ OPEX 、類似雲端的體驗）： * * 偏好 100% 的營運成本、因此資產不會最終出現在客戶的資產負債表上 * 內部 / 外部服務供應商希望將成本與使用量 / 營收一致 * 工作負載與不可預測的容量成長 * 重新配置一般儲存工作的 IT 資源（移轉、技術更新、升級、 等） * 將工作負載移轉至雲端之前的短期解決方案 * 將工作負載從雲端傳回內部部署

* NetApp Keystone 什麼是呢？*

NetApp Keystone 是一種新的靈活內部部署訂閱型採購模式。它可讓客戶消除管理資源的障礙、並完成冗長的採購週期、進而加速實現價值。Keystone 服務可讓客戶根據業務優先順序調整經濟效益。如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/keystone/index.html#netapp-keystone-flex-subscription["請按這裡"]。

*內部部署是什麼意思？*

內部部署是指客戶擁有的資料中心、或是主機代管機構中客戶擁有的空間。客戶負責空間、電力和冷卻。

Keystone 服務有哪些好處？ *

Keystone 服務的部分優點如下：

* 讓 IT 人員不再需要執行複雜的儲存相關工作、也能專注於應用程式管理
* 減少前期資本投資
* 讓客戶在不過度資源配置的情況下、也能滿足他們的需求
* 使資料儲存成本符合業務需求 / 活動
* 繞過複雜的組織採購程序、簡化基礎架構的資源配置
* 確保內部部署的資料安全無虞
* 如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/keystone/index.html#benefits-of-flex-subscription["請按這裡"]。

