---
sidebar: sidebar 
permalink: nkfsfaq_netapp_service_engine_self-service_access_portal.html 
keywords: netapp, keystone, service, engine, self-service, acess, portal, 
summary: NetApp 服務引擎 / 自助服務存取入口網站 
---
= NetApp 服務引擎 / 自助服務存取入口網站
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
下列常見問題集適用於 NetApp 服務引擎。

什麼是NetApp服務引擎？*

NetApp Service Engine 是 NetApp 營運模式中的自助服務入口網站、可讓您根據 NetApp Keystone 您的《支援 NetApp 訂閱服務」登入及配置儲存設備。此工具也會針對訂閱提供使用量層級的報告、並啟動任何服務要求或訂閱變更。

*客戶營運模式需要NetApp服務引擎？*

在客戶營運模式中、需要 NetApp 服務引擎。它提供使用量詳細資料的基本報告、並必須收集和報告帳單資訊。

* NetApp服務引擎安裝在何處？*

在 NetApp 營運的模式中、 NetApp 服務引擎會安裝在 NetApp 提供的運算資源上。在客戶操作的模式中、 NetApp 服務引擎安裝在客戶提供的運算資源上。

*誰可以登入NetApp服務引擎？*

使用者可透過 NetApp SSO 或 NetApp 服務引擎中設定的本機使用者進行驗證。

*如何控制存取？*

NetApp 服務引擎提供角色型存取控制（ RBAC ）、每位使用者都可與角色建立關聯、以定義他們可以執行哪些動作。RBAC 指派是由客戶使用 NetApp 服務引擎來完成。

*有哪些存取控制可用？*

提供下列存取控制：

* * 合作夥伴管理員 * 合作夥伴一方的系統管理員、擁有建立及管理租戶、管理租戶訂閱、檢視使用報告及管理儲存設備技術層面的權限。
* * 客戶 / 租戶管理 * 客戶方的管理人員、擁有權限可要求變更訂閱內容、建立新使用者和子租戶、以及建立及檢視檔案共用、磁碟和儲存區。
* * NetApp 管理員（讀取） * NetApp 管理員、可存取 Web 入口網站的所有元件、並可檢視所有詳細資料、例如 NetApp Keystone 所有的「更新訂閱」、合作夥伴與租戶訂閱、以及儲存設備。不過、此使用者沒有建立、編輯或刪除的權限。
* * NetApp 管理員 * 此使用者擁有完整存取權限、可在 NetApp Service Engine 入口網站執行所有功能、以管理 NetApp Keystone 《支援時局》訂閱、以及合作夥伴與租戶管理的所有活動。


*我可以在哪裡看到使用量的帳單？*

您可以在儀表板上的 * 每月費用 * 小工具中、檢視過去三個月訂閱的每月總費用。您可以按一下小工具、或瀏覽至 * 管理 * > * 帳單 * 來檢視詳細的帳單資訊。
