---
sidebar: sidebar 
permalink: nkfsfaq_service_offer_details.html 
keywords: netapp, keystone, service, offer, details, 
summary: 服務供應詳細資料 
---
= 彈性訂閱服務優惠詳細資料
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
下列問題可解答您對於 NetApp Keystone 《恆時資訊訂閱》服務產品的常見問題。

*最小承諾容量是多少？*

針對一個或多個服務層、每個站台提交的最小 NetApp Keystone 容量為 100 TiB （ Flex訂購 ）。

*彈性訂閱協議的一般期限為何？*

彈性訂購方案提供 12 、 24 及 36 個月的期限。

*如何存取儲存設備？*

在 NetApp 營運（標準）模式中、儲存控制器（ ONTAP 系統管理程式或系統管理存取權）由 NetApp 擁有及管理。您只能透過 NetApp 服務引擎 UI 和 API 來監控及管理儲存設備。在客戶管理（或精簡）部署中、 NetApp 服務引擎 UI 和 API 主要用於計費功能、您可以存取儲存控制器、例如 Active IQ Unified Manager ：功能不受限的功能、例如功能不受限的功能、 ONTAP 也可以直接存取 ONTAP 功能不受限的叢集。

*如何管理服務？*

NetApp Service Engine 是協調與管理工具、可讓您用來配置儲存設備、並取得服務使用量的報告。

*如何增加訂閱的承諾容量？*

您可以透過 NetApp 服務引擎管理工具或 NetApp Keystone 其支援中心經理提交容量新增申請。

*增加容量是否會延長期限？*

所有新增項目均為現有期間的共同期限、但申請必須在訂閱的最後 90 天內提出、在此情況下、期限必須延長至少 12 個月。

*訂閱是否可以與其他訂閱者共同訂閱？*

否、訂閱條款彼此獨立。

*我可以將備份儲存設備新增至現有的訂閱嗎？*

在備份使用案例中、您可以將現有或新服務層級的容量新增至現有訂閱、包括標準或價值服務層級。這不會改變現有訂閱的期限。不過有一點要注意的是、如果您想要在訂閱期限的最後90天（即訂閱結束前的最後90天）內新增容量、您也必須將訂閱續約至少一年。

*新的訂閱是否具有彈性、可隨新的一年一度續訂？*

是的、新的訂閱可以有新的條款與任何現有的訂閱分開。

*租戶訂閱條款是否可延伸至合作夥伴的訂閱期限之外？*

租戶訂閱可延伸至合作夥伴目前的 Flex 訂閱期限之外。建立訂閱時、以及使用量報告中、都會顯示警告。

*我可以在同ONTAP 一個支援叢集上混合多個訂閱嗎？*

否、每個叢集都會指派給特定的訂閱。

*監控與營運的對象是誰？*

對於 NetApp 營運的服務、 NetApp 負責遠端監控基礎架構、以便根據議定的期望提供服務。

對於合作夥伴營運的服務、合作夥伴負責遠端監控基礎架構、以便根據議定的期望提供服務。

對於客戶營運的服務、客戶負責監控基礎架構、並向 NetApp 提出任何問題。

*如果我提早終止服務、會發生什麼事？*

最低服務承諾為 12 個月。如果您提早取消服務、則必須事先支付剩餘價值。

*是否有機會在初始期限結束後轉換成購買項目？*不可以此優惠不包含轉換為購買的選項。此外、先前購買的 NetApp 產品不在本方案範圍之內。

*我可以申請特定的軟體版本嗎？*

不可以整個客戶群的軟體版本均已標準化。 NetApp Keystone

*是否會收到軟體升級的通知？*

是的。所有的維護 / 升級活動都會在 NetApp Keystone 雙方同意的時間與客戶溝通、並由「更新成功經理」安排。
