---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: FlexFlex 訂閱 NetApp Keystone
    url: "/index.html"
    entries:
    - title: 服務條款與說明
      url: "/nkfsosm_service_terms_and_description_overview.html"
      entries:
      - title: 服務容量定義
        url: "/nkfsosm_keystone_service_capacity_definitions.html"
      - title: 效能服務層級或服務層級
        url: "/nkfsosm_performance.html"
      - title: 服務層級指標與定義
        url: "/nkfsosm_service_level_metrics_and_definitions.html"
      - title: 帳單
        url: "/nkfsosm_kfs_billing.html"
      - title: 資料保護
        url: "/nkfsosm_data_protection.html"
      - title: 分層
        url: "/nkfsosm_tiering.html"
      - title: 不可退回的磁碟
        url: "/nkfsosm_nrd.html"
      - title: 美國公民支援
        url: "/nkfsosm_uscs.html"
      - title: Flex 訂閱與 Equinix
        url: "/nkfsosm_equinix.html"
    - title: 營運模式與責任
      url: "/nkfsosm_overview.html"
    - title: 租賃與多租戶共享
      url: "/nkfsosm_tenancy_overview.html"
    - title: 彈性訂閱基礎架構
      url: "/nkfsosm_keystone_service_delivery_architecture_overview.html"
    - title: 站台需求
      url: "/nkfsosm_site_requirements.html"
    - title: 營運
      url: "/nkfsosm_netapp_global_services_and_support_center_@gssc@.html"
    - title: Flex 訂閱與 Active IQ 功能
      url: "/nkfsosm-keystone-and-aiq.html"
  - title: 版本資訊
    entries:
    - title: 新增功能
      url: "/rn_whats_new.html"
    - title: 修正問題
      url: "/rn_fixed_issues.html"
    - title: 已知問題
      url: "/rn_known_issues.html"
  - title: 彈性訂閱常見問題集
    url: "/nkfsfaq_overview.html"
    entries:
    - title: 彈性訂閱
      url: "/nkfsfaq_keystone_subscription.html"
    - title: 服務供應詳細資料
      url: "/nkfsfaq_service_offer_details.html"
    - title: 營運模式
      url: "/nkfsfaq_operating_models.html"
    - title: NetApp 服務引擎 / 自助服務存取入口網站
      url: "/nkfsfaq_netapp_service_engine_self-service_access_portal.html"
  - title: NetApp 服務引擎 Web 介面
    url: "/sewebiug_overview.html"
    entries:
    - title: 帳單帳戶、訂閱、服務和效能
      url: "/sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html"
    - title: 開始使用
      entries:
      - title: 總覽
        url: "/sewebiug_getting_started_overview.html"
      - title: 登入
        url: "/sewebiug_log_in_to_the_netapp_service_engine_web_interface.html"
      - title: 服務供應商與客戶的角色與營運
        url: "/sewebiug_partner_service_provider.html"
      - title: 選取租戶
        url: "/sewebiug_select_tenant.html"
      - title: 檢視 NetApp 服務引擎 Web 介面
        url: "/sewebiug_netapp_service_engine_web_interface_overview.html"
    - title: 檢視 Flex 訂閱儀表板
      url: "/sewebiug_dashboard.html"
    - title: 檢視帳單
      url: "/sewebiug_billing.html"
    - title: 使用檔案服務
      url: "/sewebiug_working_with_file_services_overview.html"
      entries:
      - title: 檢視伺服器
        url: "/sewebiug_view_servers.html"
      - title: 建立檔案伺服器
        url: "/sewebiug_create_a_file_server.html"
      - title: 修改檔案伺服器
        url: "/sewebiug_modify_file_server.html"
      - title: 刪除檔案伺服器
        url: "/sewebiug_delete_file_server.html"
      - title: 檢視共享區
        url: "/sewebiug_view_shares.html"
      - title: 建立檔案共用區
        url: "/sewebiug_create_a_new_file_share.html"
      - title: 從 Snapshot 建立檔案共用
        url: "/sewebiug_create_file_share_from_snapshot.html"
      - title: 修改檔案共用區
        url: "/sewebiug_modify_a_file_share.html"
      - title: 刪除檔案共用區
        url: "/sewebiug_delete_a_file_share.html"
      - title: 建立檔案共用區的 adocad 快照
        url: "/sewebiug_create_adhoc_snapshot_of_a_file_share.html"
    - title: 使用區塊儲存設備
      url: "/sewebiug_working_with_block_storage_overview.html"
      entries:
      - title: 使用主機群組
        url: "/sewebiug_view_host_groups.html"
      - title: 檢視磁碟
        url: "/sewebiug_view_disks.html"
      - title: 建立磁碟
        url: "/sewebiug_create_a_new_disk.html"
      - title: 從快照建立磁碟
        url: "/sewebiug_create_a_disk_from_a_snapshot.html"
      - title: 修改磁碟
        url: "/sewebiug_modify_a_disk.html"
      - title: 刪除磁碟
        url: "/sewebiug_delete_a_disk.html"
      - title: 建立磁碟的 adocad 快照
        url: "/sewebiug_create_an_adhoc_snapshot_of_a_disk.html"
    - title: 使用物件儲存設備
      entries:
      - title: 總覽
        url: "/sewebiug_working_with_object_storage_overview.html"
      - title: 檢視儲存庫
        url: "/sewebiug_view_buckets.html"
      - title: 初始化物件儲存
        url: "/sewebiug_initialize_object_storage.html"
      - title: 建立貯體
        url: "/sewebiug_create_buckets.html"
      - title: 檢視物件儲存群組和使用者
        url: "/sewebiug_view_the_object_storage_group_and_users.html"
      - title: 建立物件儲存群組
        url: "/sewebiug_create_an_object_storage_group.html"
      - title: 修改物件儲存群組
        url: "/sewebiug_modify_an_object_storage_group.html"
      - title: 刪除物件儲存群組
        url: "/sewebiug_delete_an_object_storage_group.html"
      - title: 建立物件儲存使用者
        url: "/sewebiug_create_object_storage_user.html"
      - title: 修改物件儲存使用者
        url: "/sewebiug_modify_an_object_storage_user.html"
      - title: 為使用者建立 S3 金鑰
        url: "/sewebiug_create_an_s3_key_for_a_user.html"
      - title: 刪除使用者的 S3 金鑰
        url: "/sewebiug_delete_an_s3_key_for_a_user.html"
    - title: 管理雲端服務
      entries:
      - title: 管理雲端服務
        entries:
        - title: 總覽
          url: "/sewebiug_managing_subscribed_services_overview.html"
        - title: 檢視已訂閱服務的清單
          url: "/sewebiug_view_a_list_of_subscribed_services.html"
        - title: 新增訂閱的服務
          url: "/sewebiug_add_a_subscribed_service.html"
        - title: 修改訂閱的服務詳細資料
          url: "/sewebiug_modify_the_subscribed_service_details.html"
        - title: 刪除訂閱的服務
          url: "/sewebiug_delete_a_subscribed_service.html"
      - title: 管理Azure NetApp Files
        entries:
        - title: 管理Azure NetApp帳戶
          url: "/sewebiug_managing_azure_netapp_accounts.html"
        - title: 管理Azure容量資源池
          url: "/sewebiug_managing_azure_capacity_pools.html"
        - title: 管理Azure Volume
          url: "/sewebiug_managing_azure_volumes.html"
      - title: 管理Cloud Volumes Service 適用於Google Cloud Platform的功能
        url: "/sewebiug_managing_gcp_cvs.html"
    - title: 檢視報告
      url: "/sewebiug_working_with_reports.html"
    - title: 備份您的磁碟區
      url: "/sewebiug_back_up_file_shares_and_disks.html"
    - title: 管理訂閱
      url: "/sewebiug_managing_subscriptions.html"
    - title: 管理服務要求
      entries:
      - title: 總覽
        url: "/sewebiug_managing_service_requests_overview.html"
      - title: 提出服務要求
        url: "/sewebiug_raise_a_service_request.html"
      - title: 追蹤服務要求
        url: "/sewebiug_track_a_service_request.html"
      - title: 服務要求程序
        url: "/sewebiug_service_request_process.html"
    - title: 執行管理工作
      entries:
      - title: 管理使用者
        entries:
        - title: 檢視使用者清單
          url: "/sewebiug_view_a_list_of_users.html"
        - title: 新增使用者
          url: "/sewebiug_add_a_user.html"
        - title: 修改使用者詳細資料
          url: "/sewebiug_modify_user_details.html"
        - title: 刪除使用者
          url: "/sewebiug_delete_a_user.html"
      - title: 管理租戶和子租戶
        url: "/sewebiug_managing_tenants_and_subtenants.html"
      - title: 檢視及管理警示
        url: "/sewebiug_alerts.html"
    - title: 管理網路
      url: "/sewebiug_define_network_configurations.html"
  - title: NetApp 服務引擎 API 參考資料
    url: "/seapiref_overview_of_netapp_service_engine_apis.html"
    entries:
    - title: 授權與驗證
      url: "/seapiref_authorization_and_authentication.html"
    - title: NetApp 服務引擎 REST API
      url: "/seapiref_netapp_service_engine_rest_apis.html"
    - title: 消費者 API
      entries:
      - title: 總覽
        url: "/seapiref_consumer_apis_overview.html"
      - title: 雲端協調 API
        url: "/seapiref_cloud_orchestration_apis.html"
      - title: 區塊儲存 API
        url: "/seapiref_block_storage_apis.html"
      - title: 檔案服務 API
        url: "/seapiref_file_services_apis.html"
      - title: 物件儲存 API
        url: "/seapiref_object_storage_apis.html"
      - title: 備份 API
        url: "/seapiref_backups_apis.html"
      - title: 報告 API
        url: "/seapiref_reporting_apis.html"
      - title: 使用 API 建立子網路
        url: "/seapiref_subnets_apis.html"
      - title: "（使用者）管理 API"
        url: "/seapiref_@consumer@_administration_apis.html"
    - title: 系統管理員 API
      entries:
      - title: 總覽
        url: "/seapiref_administrator_apis_overview.html"
      - title: 租戶
        url: "/seapiref_tenants.html"
      - title: 子租戶
        url: "/seapiref_subtenants.html"
      - title: 使用者
        url: "/seapiref_users.html"
      - title: 區域
        url: "/seapiref_zones.html"
      - title: 區域
        url: "/seapiref_regions.html"
      - title: 叢集 ONTAP
        url: "/seapiref_ontap_clusters.html"
      - title: 執行個體 StorageGRID
        url: "/seapiref_storagegrid_instances.html"
      - title: 服務層級
        url: "/seapiref_service_levels.html"
      - title: 服務要求
        url: "/seapiref_service_requests.html"
      - title: 工作
        url: "/seapiref_jobs.html"
  - title: 法律聲明
    url: "/legal-notices.html"
