---
sidebar: sidebar 
permalink: rn_whats_new.html 
keywords: 'netapp, keystone, release notes, new features, what"s new,' 
summary: NetApp 服務引擎的新功能 
---
= 此版本 NetApp Keystone 的《更新資訊》訂閱服務有哪些新功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
版本說明會告知 NetApp Keystone 您有關推出的全新功能與增強功能、包括更新於《支援更新訂閱》（ Flex 訂購）服務、以及已知的限制與修正。



== 查看 Cloud Volumes ONTAP 您的不二使用情形與帳單（ 2021 年 12 月 5 日）

如果您是 NetApp Keystone 某位支援不限彈性訂閱（ Flex 訂閱）的客戶、而且也有 Cloud Volumes ONTAP 訂閱功能、您可以使用 Flex 訂閱來為 Cloud Volumes ONTAP 您的使用率充電、並檢視帳單和使用詳細資料。Cloud Manager 現在可以探索您的 Flex 訂閱帳戶、並在 Cloud Manager 介面上顯示詳細資料。按一下「 * 所有服務 > 數位錢包 > Keystone Flex 訂閱 * 」索引標籤、即可執行下列活動：

* 檢視歡迎畫面、您可在此要求 Flex 訂閱管理員將 Cloud Manager 使用者 ID 與您的 Flex 訂閱使用者 ID 建立關聯、進而存取 * Keystone Flex 訂閱 * 索引標籤。
* 檢視內部部署系統和 Cloud Volumes ONTAP 內部部署系統上已訂閱服務的已承諾和已用容量使用量資料。
* 檢視與 Cloud Manager 帳戶相關的 Flex 訂閱詳細資料。顯示詳細資料、例如已提交、已用及突發容量。
* 將 Cloud Volumes ONTAP 您的帳戶連結至您的 Flex 訂閱 ID 、以建立帳戶與帳單和容量使用報告的關聯。
* 申請增加或減少已提交的 Flex 訂閱服務容量。
* 檢視並使用連結的 Flex 訂閱 ID 作為收費方法、以計費 Cloud Volumes ONTAP 使用費（僅限連結 ID ）。


如需詳細資訊、請參閱 Cloud Manager 文件中的下列連結：link:https://docs.netapp.com/us-en/occm/concept_licensing.html#keystone-flex-subscription["Keystone Flex 訂閱"]
link:https://docs.netapp.com/us-en/occm/task_managing_licenses.html#manage-keystone-flex-subscriptions["管理 Keystone Flex 訂閱"]

｛ sp ｝ + ｛ sp ｝ + ｛ sp ｝ 不同版本的 NetApp 服務引擎已推出下列功能、以支援 NetApp Keystone 透過《支援使用效益管理訂閱》（ Flex 訂閱）提供的增強功能：



== NetApp Service Engine 2.2 中介紹的功能

此版本的新功能包括全新的儀表板、適用於新的小工具、包括帳單、容量使用率、服務要求和警示。此版本也包含新的帳單和警示管理畫面、以及將訂閱的服務功能表重新命名為 Cloud Services 。



=== 增強的儀表板檢視

NetApp 服務引擎儀表板經過重新設計、包含下列新元件：

* * 容量使用率 * 、用於檢視您所訂閱服務的已用容量。
* * 每月費用（帳單） * 、用於檢視您所有訂閱的每月總費用。
* * 警示 * ：檢視環境中最新警示的摘要。
* * 服務要求 * 、用於檢視環境中最近產生的服務要求清單。如需詳細資訊、請參閱 link:sewebiug_dashboard.html["檢視 Flex 訂閱儀表板"]。




=== 新的帳單畫面

新增了一個 * 帳單 * 畫面、可輕鬆存取及計算您的歷史帳單資料。此畫面提供與您所有訂閱服務相關的每月費用全方位檢視。

請從儀表板上的 * 每月費用 * 小工具瀏覽此畫面、或從 * 管理 > 帳單 * 檢視每月訂閱層級的費用細分、以查看您所有訂閱服務的費用。計費資料是根據您的承諾和突發容量使用量而定、可在前幾個月內供您使用。如需詳細資訊、請參閱 link:sewebiug_billing.html["檢視帳單"]。



=== 新警示畫面

此版本中引入了一個新的 * 警示 * 畫面、其中列出所有系統產生和使用者產生的警示。此畫面也可讓您針對環境相關的重大事件建立自訂警示訊息、並將其傳達給其他使用者。他們可以視需要檢視和關閉警示。如需詳細資訊、請參閱 link:sewebiug_alerts.html["建立及管理警示"]。



=== 增強的使用者介面

NetApp Service Engine 使用者介面已進行下列增強功能：

* 左側導覽窗格上的 * 儀表板 * 功能表提供直覺式導覽點、可存取儀表板。
* 左導覽窗格上的 * 已訂閱服務 * 功能表已重新命名為 * Cloud Services* 。+ + +




== NetApp Service Engine 2.1 中介紹的功能

此版本的新功能包括支援 Flex 訂閱環境中的多租戶共享、以及可協助將非使用中資料移至成本較低的本機或雲端層的分層功能。



=== 介紹適用於服務供應商的 Flex 訂閱服務

NetApp 服務引擎現在支援服務供應商管理多租戶環境。您可以執行資源配置、報告、帳單及管理擁有自己訂閱的客戶等功能。為了支援此功能、我們進行了下列增強功能：

* * 儀表板： * 儀表板會針對特定訂閱編號顯示儲存訂閱資訊、例如服務層級、每個服務層級的容量使用量、以及附加資料保護服務。身為服務供應商、您可以檢視 NetApp Keystone 您的《更新訂閱》和租戶訂閱的詳細資料。身為租戶管理員、您可以檢視您租戶的所有租戶訂閱詳細資料。
* * 報告： * 您可以針對 NetApp Keystone 使用情形及租戶使用情況、建立容量與效能報告。身為合作夥伴管理員、您可以從 * Reports > * Keystone usage* 檢視 Flex 訂閱使用量的容量報告。身為合作夥伴管理員、您可以從 * Reports > * Tenant usage* / * Capacity usage* 檢視特定租戶的容量使用量報告。身為租戶管理員、您可以從 * 報告 * > * 租戶使用情況 * 檢視租戶使用情況報告。
* * 訂閱： * 身為合作夥伴管理員、您可以分別從 * 訂閱 * > * 基礎概念訂閱 * 與 * 訂閱 * > * 租戶訂閱 * 檢視及更新您的彈性訂閱與租戶訂閱。身為租戶管理員、您只能檢視租戶訂閱。
* * 使用者： * 根據您的角色、您可以根據需求、將權限指派給租賃中的新使用者或現有使用者。角色可以是 NetApp 管理員、具有唯讀權限的 NetApp 管理員、合作夥伴管理員或租戶管理員。身為合作夥伴管理員、您只能將合作夥伴管理員或租戶管理員角色指派給新使用者。租戶管理員使用者只能將租戶管理員角色指派給其他使用者。
* * 網路功能表： * 身為合作夥伴管理員、您可以檢視為租賃所定義的網路。您也可以從 * 網路 * > * 子網路 * 建立子租戶和區域的子網路。這是終端客戶或子租戶在配置儲存設備時所需的。
* API 支援：本版本提供「 / 租戶 / ｛ 租戶 ID ｝ / 區域 / ｛ zo_name ｝ / 子網路」和「 / 租戶 / ｛ 租戶 ID ｝ / 區域 / ｛ zion_name ｝ / 子網路 / ｛ id ｝ / 標籤」 API 、以建立及檢視子租戶的子網路。


如需此功能的詳細資訊、請參閱下列連結：

* link:nkfsosm_overview.html["營運模式、角色和責任"]
* link:nkfsosm_tenancy_overview.html["Flex 訂閱中的租賃與多租戶"]
* link:sewebiug_dashboard.html["檢視 Flex 訂閱儀表板"]
* link:sewebiug_working_with_reports.html["檢視報告"]
* link:sewebiug_managing_subscriptions.html["管理訂閱"]
* link:sewebiug_managing_tenants_and_subtenants.html["管理租戶和租戶"]
* link:sewebiug_define_network_configurations.html["定義租戶和子租戶的網路"]




=== 分層

現在、支援的功能包括運用 NetApp 技術的分層功能。 NetApp Keystone FabricPool它可識別較不常用的資料、並將其分層至由 NetApp 擁有、部署及管理的內部部署冷儲存設備。您可以訂閱極致分層或優質分層的效能等級、以選擇分層。

下列 API 已經過修改、納入新分層服務層級的新屬性值：

* 檔案服務 API
* 區塊儲存區 API


如需詳細資訊、請參閱下列連結：

* link:nkfsosm_tiering.html["分層"]
* link:nkfsosm_performance.html["效能服務層級"]


｛ sp ｝ + ｛ sp ｝ + ｛ sp ｝



== NetApp Service Engine 2.0.1 中介紹的功能

此版本的新功能包括：



=== 支援 Google Cloud Platform 的 Cloud Volumes Services

NetApp Service Engine 現在除了現有 Azure NetApp Files 的支援功能之外、還能支援 Cloud Volumes Services for Google Cloud Platform （ GCP ）。您現在可以從 NetApp 服務引擎管理訂閱的服務、以及配置和修改 Google Cloud Volumes 。


NOTE: Cloud Volumes 服務的訂閱是在 NetApp 服務引擎之外進行管理。相關認證資料會提供給 NetApp 服務引擎、以便連線至雲端服務。



=== 能夠管理 NetApp 服務引擎以外的資源配置

客戶環境中已存在且屬於 NetApp 服務引擎中設定之儲存 VM 的磁碟區（磁碟和檔案共用）、現在可作為 NetApp Keystone 您的《支援 NetApp 訂閱》（ Flex 訂閱）的一部分來檢視和管理。NetApp 服務引擎以外配置的磁碟區現在會以適當的狀態代碼列在「 * 共享區 * 」和「 * 磁碟 * 」頁面上。背景程序會定期執行、並在您的 NetApp 服務引擎執行個體中匯入外部工作負載。

匯入的磁碟和檔案共用可能與 NetApp 服務引擎上現有的磁碟和檔案共用不相同。匯入之後、這些磁碟和檔案共用會分類為「非標準」狀態。您可以從 * 支援 > 服務要求 > 新服務要求 * 提出服務要求、以便透過 NetApp 服務引擎入口網站進行標準化與管理。



=== 與 NetApp 服務引擎整合 SnapCenter

作爲與 NetApp 服務引擎進行完整性整合的一部分 SnapCenter 、您現在可以從 SnapCenter NetApp 服務引擎執行個體以外的您的支援環境所建立的 Snapshot 複製磁碟和檔案共用。從 NetApp 服務引擎入口網站上的現有 Snapshot 複製檔案共用區或磁碟時、會列出這些 Snapshot 供您選擇。擷取程序會在背景中定期執行、以便在 NetApp 服務引擎執行個體中匯入 Snapshot 。



=== 維護備份的新畫面

全新的 * 備份 * 畫面可讓您檢視及管理環境中所建立之磁碟和檔案共用的備份。您可以編輯備份原則、中斷與來源磁碟區的備份關係、以及刪除具有所有恢復點的備份磁碟區。此功能可保留備份（做為孤立備份）、即使來源磁碟區已刪除、也可於稍後還原。若要從特定的還原點還原檔案共用區或磁碟、您可以從 * 支援 > 服務要求 > 新服務要求 * 提出服務要求。



=== 限制使用者存取 CIFS 共用區的資源

您現在可以指定存取控制清單（ ACL ）來限制 CIFS （ SMB ）或多重傳輸協定共用區的使用者存取。您可以根據 Active Directory （ AD ）設定來指定 Windows 使用者或群組、以新增至 ACL 。link:https://docs.netapp.com/us-en/keystone/sewebiug_create_a_new_file_share.html#steps["深入瞭解"]。



== NetApp Service Engine 2.0 中介紹的功能

此版本的新功能包括：



=== 支援 MetroCluster

NetApp Service Engine 支援以 MetroCluster 各種功能組態設定的站台。支援不中斷儲存的同步鏡射功能、可提供恢復點目標（ RPO ） 0 或恢復時間目標（ RTO ） 0 的資料保護功能。 MetroCluster ONTAP支援可轉譯為 NetApp 服務引擎內的同步災難恢復功能。 MetroCluster每一邊 MetroCluster 的一個實例都會登錄為個別的區域、每個區域都有自己的訂閱、其中包含資料保護進階費率計畫。在啟用 MetroCluster 的區域中建立的共用或磁碟、會同步複寫到第二個區域。複寫區域的使用量遵循適用於已配置儲存設備之區域的資料保護進階速率計畫。



=== Cloud Volumes 服務支援

NetApp 服務引擎現在有能力支援 Cloud Volumes Services 。它現在可以支援 Azure NetApp Files 功能不只是功能不一。


NOTE: Cloud Volumes 服務的訂閱是在 NetApp 服務引擎之外進行管理。相關認證資料會提供給 NetApp 服務引擎、以便連線至雲端服務。

NetApp 服務引擎支援：

* 配置或修改 Cloud Volumes Services 磁碟區（包括擷取快照的能力）
* 將資料備份到 Cloud Volumes Services 區域
* 檢視 NSE 庫存中的 Cloud Volumes Services Volume
* 檢視 Cloud Volumes Services 使用量。




=== 主機群組

NetApp 服務引擎支援使用主機群組。主機群組是一組 FC 傳輸協定主機全球連接埠名稱（ WWPN ）或 iSCSI 主機節點名稱（ IQN ）。您可以定義主機群組並將其對應至磁碟、以控制哪些啟動器可以存取磁碟。主機群組取代了為每個磁碟指定個別啟動器的需求、並允許下列項目：

* 將另一個磁碟顯示給同一組啟動器
* 在多個磁碟上更新啟動器集




=== 突發使用量與通知

部分 NetApp 服務引擎支援的儲存訂閱可讓客戶使用超出其承諾容量的突發容量、此容量會在訂閱的承諾容量之外另行收費。使用者必須瞭解何時該使用或使用突發容量來控制使用量和成本。



==== 建議的變更會導致使用突發容量時發出通知

顯示建議資源配置變更的通知、會導致訂閱量暴增。使用者可以選擇繼續、因為他們知道訂閱將會爆發、或選擇不繼續執行此動作。link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#burst-usage-notifications["深入瞭解"]。



==== 訂閱量暴增時發出通知

當訂閱量暴增時、會顯示通知橫幅。link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#burst-usage-notifications["深入瞭解"]。



==== 容量報告會顯示尖峰使用量

容量報告、顯示訂閱量暴增的天數和使用的突發容量量。link:sewebiug_working_with_reports.html#capacity-usage["深入瞭解"]。



=== 效能報告

NetApp Service Engine 網路介面中的新效能報告會顯示個別磁碟或共用的效能資訊、並以下列效能評量為準：

* IOPS/TiB （每秒每個 TB 的輸入 / 輸出作業）：儲存設備上每秒的輸入和輸出作業（ IOPS ）發生率。
* 處理量（以 Mbps 為單位）：往返儲存媒體的資料傳輸率（以每秒 MB 為單位）。
* 延遲（毫秒）：從磁碟或共用區讀取和寫入的平均時間（毫秒）。




=== 訂購管理

訂閱管理功能已增強。您現在可以：

* 申請資料保護附加元件、或申請訂閱或服務的額外資料保護附加元件容量
* 檢視資料保護使用容量




=== 帳單強化

帳單現在支援測量 ONTAP 及計費功能、以利使用 Snapshot （檔案和區塊）儲存設備。



=== 隱藏的 CIFS 共用區

NetApp 服務引擎支援建立隱藏的 CIFS 共用區。
