---
sidebar: sidebar 
permalink: seapiref_users.html 
keywords: netapp, keystone, users, 
summary: Keystone 使用者 
---
= 使用者
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用下表所列的方法擷取、建立、修改及刪除子租戶。

|===
| HTTP 方法 | 路徑 | 說明 


| 《 Get 》（取得） | /v2.1 / 使用者 | 擷取所有使用者的清單。 


| 《 Get 》（取得） | v2.1 / 使用者 / ｛ id ｝ | 依使用者 ID 擷取使用者。 


| 貼文 | /v2.1 / 使用者 | 建立新使用者。 


| 《投入》 | v2.1 / 使用者 / ｛ id ｝ | 修改使用者的詳細資料。 


| " 刪除 " | v2.1 / 使用者 / ｛ id ｝ | 刪除使用者。 


| 《 Get 》（取得） | 「 v2.1 / 使用者 / ｛ userName ｝ 」 | 依使用者名稱擷取使用者。 
|===


=== 使用者屬性

下表列出使用者屬性。

|===
| 屬性 | 類型 | 說明 


| "id" | 字串 | 使用者的唯一識別碼。 


| 《使用者名稱》 | 字串 | 使用者名稱。 


| 密碼 | 字串 | 使用者密碼。 


| 「名字」 | 字串 | 使用者的名字。 


| 「 lastName 」 | 字串 | 使用者的姓氏。 


| 「 DisplayName 」 | 字串 | 使用者的顯示名稱。 


| 電子郵件 | 字串 | 使用者的電子郵件地址。 


| 電話 | 字串 | 使用者的電話號碼。 


| 「 profileImageURL 」 | 字串 | 使用者設定檔映像的 URL 。 


| 租戶 ID | 字串 | 此使用者的主要租戶識別碼。 


| 《租賃》 | –  a| 
使用者所屬的租戶；由下列項目組成的陣列：

* 「租戶 ID 」、以及
* 「 role 名稱」這是使用者角色、其中一位是使用者、 admin 、 read 、合作夥伴、 或 root 。




| 《供應商》 | 字串 | 驗證供應商：「本機」或「 ActiveDirectory 」 


| 《供應商資料》 | –  a| 
驗證供應商詳細資料、包括：

* 「 email_address' 」、以及
* 「 Mo_of 」（群組成員資格）


|===


=== 擷取所有使用者

使用下表所列的方法擷取所有使用者。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《 Get 》（取得） | /v2.1 / 使用者 | 擷取所有使用者。 | 無 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5dddbe0ef071fe0001b889fd",
        "username": "TestUser3",
        "firstName": "Test",
        "lastName": "User",
        "displayName": "",
        "email": "testuser@netapp.com",
        "tenancies": [
          {
            "id": "5d914499869caefed0f39eee",
            "name": "MyOrg",
            "code": "myorg",
            "role": "admin"
          }
        ]
      }
    ]
  }
}
....


=== 依 ID 擷取使用者

使用下表所列的方法、依 ID 擷取使用者。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《 Get 》（取得） | /v2.1 / 使用者 | 依 ID 擷取使用者。 | 「 ID （字串）」：使用者的唯一識別碼。 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e585df6896bd80001dd4b44",
        "username": "testuser01",
        "firstName": "",
        "lastName": "",
        "displayName": "",
        "email": "",
        "tenancies": [
          {
            "id": "5d914499869caefed0f39eee",
            "name": "MyOrg",
            "code": "myorg",
            "role": "user"
          }
        ]
      }
    ]
  }
}
....


=== 依使用者名稱擷取使用者

使用下表所列的方法、依使用者名稱擷取使用者。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《 Get 》（取得） | /v2.1 / 使用者 | 依使用者名稱擷取使用者。 | 「 UserName （字串）」：使用者的使用者名稱。 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e61aa814559c20001df1a5f",
        "username": "MyName",
        "firstName": "MyFirstName",
        "lastName": "MySurname",
        "displayName": "CallMeMYF",
        "email": "user@example.com",
        "tenancies": [
          {
            "id": "5e5f1c4f253c820001877839",
            "name": "MyTenant",
            "code": "testtenantmh",
            "role": "user"
          }
        ]
      }
    ]
  }
}
....


=== 建立使用者

使用下表所列的方法來建立使用者。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 貼文 | /v2.1 / 使用者 | 建立新使用者。 | 無 
|===
必要的申請本文屬性：「使用者名稱」、「租戶 ID 」、「租賃、供應商」

* 索取本文範例： *

....
{
  "username": "MyUser",
  "password": "mypassword",
  "firstName": "My",
  "lastName": "User",
  "displayName": "CallMeMyUser",
  "email": "user@example.com",
  "phone": "string",
  "profileImageURL": "string",
  "tenant_id": "5e7c3af7aab46c00014ce877",
  "tenancies": [
    {
      "tenant_id": "5e7c3af7aab46c00014ce877",
      "role_name": "admin"
    }
  ],
  "provider": "local",
  "provider_data": {
    "email": "user@example.com",
    "member_of": "string"
  }
}
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed6f463129e5d000102f7e1",
        "username": "MyUser",
        "firstName": "My",
        "lastName": "User",
        "displayName": "CallMeMyUser",
        "email": "user@example.com",
        "tenancies": [
          {
            "id": "5e7c3af7aab46c00014ce877",
            "name": "MyTenant",
            "code": "mytenantcode",
            "role_name": "admin"
          }
        ]
      }
    ]
  }
}
....


=== 依 ID 修改使用者

使用下表所列的方法、依使用者 ID 修改使用者。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《投入》 | v2.1 / 使用者 / ｛ id ｝ | 修改使用者 ID 所識別的使用者。您可以修改使用者名稱、顯示名稱、密碼、電子郵件地址、電話號碼、 設定檔映像 URL 和租戶詳細資料。 | 「 ID （字串）」：使用者的唯一識別碼。 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
{
  "password": "MyNewPassword",
   "firstName": "MyFirstName",
   "lastName": "MySurname",
   "displayName": "CallMeMYF",
   "email": "user@example.com",
   "phone": "string",
  "profileImageURL": "string",
  "tenant_id": "5e5f1c4f253c820001877839",
  "tenancies": [
    {
      "tenant_id": "5e5f1c4f253c820001877839",
      "role_name": "user"
    }
  ]
}
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e61aa814559c20001df1a5f",
        "username": "MyName",
        "firstName": "MyFirstName",
        "lastName": "MySurname",
        "displayName": "CallMeMYF",
        "email": "user@example.com",
        "tenancies": [
          {
            "id": "5e5f1c4f253c820001877839",
            "name": "MyTenant",
            "code": "testtenantmh",
            "role": "user"
          }
        ]
      }
    ]
  }
}
....


=== 依 ID 刪除使用者

使用下表所列的方法、依 ID 刪除使用者。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| " 刪除 " | 「 v2.1 / 使用者 / ｛ name ｝ 」 | 刪除 ID 所識別的使用者。 | 「 ID （字串）」：使用者的唯一識別碼。 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
No content for succesful delete
....