---
sidebar: sidebar 
permalink: seapiref_zones.html 
keywords: netapp, keystone, zones, 
summary: Keystone 區域 
---
= 區域
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用下表所列的方法來建立、修改及刪除區域。如需可讓您擷取區域的 API 、請參閱（消費者）管理 API 。

|===
| HTTP 方法 | 路徑 | 說明 


| 貼文 | /v2.1 / 區域 | 建立新的區域。 


| 《投入》 | /`v2.1 / 區域 /{name} | 修改區域的詳細資料。 


| " 刪除 " | /`v2.1 / 區域 /{name} | 刪除區域。 
|===


=== 區域屬性

下表列出區域屬性。

|===
| 屬性 | 類型 | 說明 


| "id" | 字串 | 區域的唯一識別碼。 


| 名稱 | 字串 | 區域名稱。 


| 「描述」 | 字串 | 區域的說明。 


| "REGion_name" | 字串 | 區域所在區域的名稱。 
|===


=== 擷取所有區域

使用下表所列的方法擷取所有區域或區域子集。指定區域只會傳回屬於該租戶的區塊存放區。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《 Get 》（取得） | /v2.1 / 區域 | 擷取區域。 | （選用）區域名稱（字串）「 offset 」（偏移）和「 limit 」（限制）–請參閱 link:seapiref_netapp_service_engine_rest_apis.html#pagination>["常見分頁"] 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 5,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 2,
    "limit": 1,
    "records": [
      {
        "id": "5ce5d919b68d3b82dc34bef2",
        "name": "au-west1-a",
        "description": "au-west1-a",
        "region": "au-west1"
      }
    ]
  }
....


=== 依名稱擷取區域

使用下表所列的方法、依區域名稱擷取區域。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《 Get 》（取得） | /`v2.1 / 區域 /{name} | 依名稱擷取區域。 | 「 Name （ string ）（名稱（字串））」：區域名稱 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ce5d919b68d3b82dc34bef2",
        "name": "au-west1-a",
        "description": "au-west1-a",
        "region": "au-west1"
      }
    ]
  }
}
....


=== 建立區域

使用下表所列的方法建立區域。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 貼文 | /v2.1 / 區域 | 在區域內建立新的區域。 | 無 
|===
必要的要求本文屬性：「 name 」、「 description 」、「 rition_name 」

* 索取本文範例： *

....
{
  "name": "MyZoneName",
  "description": "DescriptionOfMyZone",
  "region_name": "MyRegionName"
}
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e61741c9b64790001fe9663",
        "name": "MyZoneName",
        "description": "DescriptionOfMyZone",
        "region": "MyRegionName"
      }
    ]
  }
}
....


=== 修改區域

使用下表所列的方法來修改區域。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《投入》 | /`v2.1 / 區域 ｛ name ｝ ' | 修改依名稱識別的區域。 | 名稱（字串）：區域名稱。 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
{
  "name": "MyZoneName",
  "description": "NewDescriptionOfMyZone"
}
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e61741c9b64790001fe9663",
        "name": "MyZoneName",
        "description": "NewDescriptionOfMyZone",
        "region": "MyRegionName"
      }
    ]
  }
}
....


=== 刪除區域

使用下表所列的方法刪除區域。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| " 刪除 " | /`v2.1 / 區域 ｛ name ｝ ' | 刪除以名稱識別的單一區域。必須先刪除區域內的所有儲存資源。 | 名稱（字串）：區域名稱。 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

成功刪除後沒有內容可傳回。
