---
sidebar: sidebar 
permalink: seapiref_@consumer@_administration_apis.html 
keywords: netapp, keystone, consumer, administration, apis, 
summary: Keystone （使用者）管理 API 
---
= （使用者）管理 API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
（使用者）管理 API 包含可讓您執行下列工作的方法：

* 登入、設定密碼、然後重新整理驗證權杖。
* 擷取工作並檢視工作詳細資料。
+
請參閱 link:seapiref_jobs.html#retrieve-jobs["擷取工作"] 和 link:seapiref_jobs.html#retrieve-a-job-by-job-id["依工作 ID 擷取工作"]。

* 擷取區域。
+
請參閱 link:seapiref_regions.html#retrieve-regions["擷取區域"] 和 link:seapiref_regions.html#retrieve-a-region-by-name["依名稱擷取區域"]。

* 擷取服務層級。
+
請參閱 link:seapiref_service_levels.html#retrieve-service-levels["擷取服務層級"] 和 link:seapiref_service_levels.html#retrieve-service-levels-by-name["依名稱擷取服務層級"]。

* 與子租戶合作。
+
請參閱：

+
** link:seapiref_subtenants.html#retrieve-all-subtenants["擷取所有子租戶"]
** link:seapiref_subtenants.html#retrieve-a-subtenant-by-id["依 ID 擷取子租戶"]
** link:seapiref_subtenants.html#modify-a-subtenant-by-id["修改子租戶"]
** link:seapiref_subtenants.html#delete-a-subtenant-by-id["依 ID 刪除子租戶"]


* 與子租戶合作。
+
請參閱：

+
** link:seapiref_tenants.html#retrieve-all-tenants["擷取所有租戶"]
** link:seapiref_tenants.html#retrieve-a-tenant-by-id["依 ID 擷取租戶"]
** link:seapiref_tenants.html#create-a-tenant["建立租戶"]
** link:seapiref_tenants.html#modify-the-tenant["修改租戶"]
** link:seapiref_tenants.html#delete-the-tenant["刪除租戶"]


* 擷取使用者。
+
link:seapiref_users.html#retrieve-all-users["擷取所有使用者"]、 link:seapiref_users.html#retrieve-a-user-by-id["依 ID 擷取使用者"]和 link:seapiref_users.html#retrieve-a-user-by-user-name["依使用者名稱擷取使用者"]。

* 擷取區域。
+
請參閱 link:seapiref_zones.html#retrieve-all-zones["擷取所有區域"] 和 link:seapiref_zones.html#retrieve-a-zone-by-name["依名稱擷取區域"]



下表列出本節所記錄的使用者 API 。

|===
| HTTP 方法 | 路徑 | 說明 


| 貼文 | /`v2.1 / 驗證 / 密碼 ' | 設定使用者的密碼。 


| 貼文 | /`v2.1 / 驗證 / 密碼 ' | 重新整理驗證 JWT 。 


| 貼文 | /`v2.1 / 驗證 / 登入 ' | 登入。 


| 《 Get 》（取得） | /v2.1 / 驗證 / 地區 | 擷取區域。 


| 《 Get 》（取得） | /`v2.1 / 驗證 / 地區 / ｛ name ｝ ' | 依名稱擷取區域。 


| 《 Get 》（取得） | /`v2.1 / 驗證 / 區域 | 擷取區域。 


| 《 Get 》（取得） | /`v2.1 / 驗證 / 區域 / ｛ name ｝ ' | 依名稱擷取區域。 


| 《 Get 》（取得） | /v2.1 / jobs/' | 擷取工作。 


| 《 Get 》（取得） | /`v2.1 / 工作 / ｛ id ｝ ' | 依 ID 擷取工作。 
|===


== 重設使用者密碼

使用下表所列的方法重設使用者密碼。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 貼文 | /`v2.1 / 驗證 / 密碼 ' | 重設密碼。 | 無 
|===
必要的要求內容屬性：「 UserName 」（字串）、「 new_password 」（字串）

* 索取本文範例： *

....
{
  "username": "MyName",
  "old_password": "oldPassword",
  "new_password": "newPassword"
}
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "user": {
          "id": "5e61aa814559c20001df1a5f",
          "username": "MyName",
          "firstName": "MyFirstName",
          "lastName": "MySurname",
          "displayName": "CallMeMYF",
          "email": "user@example.com",
          "tenancies": [
            {
              "id": "5e5f1c4f253c820001877839",
              "name": "MyTenant",
              "code": "testtenantmh",
              "role": "user"
            }
          ]
        },
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik15TmFtZSIsImV4cCI6MTU4MzgxNjg3MX0.ZuRXjDPVtc2pH-e9wqgmszVKCBYS2PLqux2YwQ5uoAM"
      }
    ]
  }
}
....


== 重新整理驗證權杖

使用下表所列的方法來重新整理驗證權杖。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 貼文 | /`v2.1 / 驗證 / 重新整理 ' | 重新整理驗證權杖。 | 無 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "user": {
          "id": "5d914547869caefed0f3a00c",
          "username": "myusername",
          "firstName": "myfirstname",
          "lastName": "",
          "displayName": "Myfirstname Mysurname",
          "email": "",
          "tenancies": [
            {
              "id": "5d914499869caefed0f39eee",
              "name": "MyOrg",
              "code": "myorg",
              "role": "admin"
            },
            {
              "id": "5d9417aa869caefed0f7b4f9",
              "name": "ABCsafe",
              "code": "abcsafe",
              "role": "admin"
            }
          ]
        },
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVsbGlvdCIsImV4cCI6MTU4MzgxNzA2N30.FdKD3QhPoNdWdbMfZ0bzCMTHluIt6HNP311F482K9AY"
      }
    ]
  }
}
....


== 登入

請使用下表所列的方法登入。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 貼文 | /`v2.1 / 驗證 / 登入 ' | 以使用者身分登入。 | 無 
|===
必要的要求內容屬性：「 UserName 」（字串）、「 new_password 」（字串）

* 索取本文範例： *

....
{
  "username": "MyName",
  "password": "newPassword"
}
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Authentication succeeeded.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "user": {
          "id": "5e61aa814559c20001df1a5f",
          "username": "MyName",
          "firstName": "MyFirstName",
          "lastName": "MySurname",
          "displayName": "CallMeMYF",
          "email": "user@example.com",
          "tenancies": [
            {
              "id": "5e5f1c4f253c820001877839",
              "name": "MyTenant",
              "code": "testtenantmh",
              "role": "user"
            }
          ]
        },
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik15TmFtZSIsImV4cCI6MTU4MzgxNzQwMH0._u_UyYrzg_RewF-9ClIGoKQhfZYWrixZYBrsj1kh1hI"
      }
    ]
  }
}
....