---
sidebar: sidebar 
permalink: seapiref_service_levels.html 
keywords: netapp, keystone, service, levels, 
summary: Keystone 服務層級 
---
= 服務層級
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用下表所列的方法擷取、建立、修改及刪除服務層級。

|===
| HTTP 方法 | 路徑 | 說明 


| 《 Get 》（取得） | /v2.1 / 服務層級 | 擷取所有服務層級。 


| 《 Get 》（取得） | 「 v2.1 / 服務層級 / ｛ id ｝ 」 | 依 ID 擷取服務層級。 


| 貼文 | /v2.1 / 服務層級 | 建立新的服務層級。 


| 《投入》 | 「 v2.1 / 服務層級 / ｛ id ｝ 」 | 依 ID 修改服務層級詳細資料。 


| " 刪除 " | 「 v2.1 / 服務層級 / ｛ id ｝ 」 | 刪除服務層級。 
|===


== 服務層級屬性

下表列出服務層級屬性。

|===
| 屬性 | 類型 | 說明 


| "id" | 字串 | 服務層級的唯一識別碼。 


| 名稱 | 字串 | 服務層級名稱。 


| 「描述」 | 字串 | 服務層級的描述。 


| "policy_name" | 字串 | 服務層級服務品質（ QoS ）名稱。允許的值： NSE_Value 、 nse_standard 、 nse_Performance 和 nse_Extreme 。 


| 「可用」 | 布林值 | 指出服務層級是否可供使用。 


| 《老奶奶》 | 布林值 | 指出服務層級是否已淘汰。 


| "Peak IOPS _per _tb" | 整數 | 每個 TiB 的最大可能 IOPS 。 


| "Expeted_IOPS _per _tb" | 整數 | 每個 TiB 的預期 IOPS 下限。 


| 《絕對最小 IOPS 》 | 整數 | 當預期 IOPS 低於此值時、作為置換的絕對最低 IOPS 。 


| 尖峰 IOPS 分配 | 字串 | IOPS 尖峰配置。允許的值： allocated 空間和已用空間。 


| "io_block_size_kb" | 整數 | I/O 區塊大小（ KiB ）。 


| "M_Size_GB" | 整數 | 最小大小（ GiB ）。 


| "Marax_Size_GB" | 整數 | 最大大小（ GiB ）。 


| "Marax_Peak IOPS （最大值） " | 整數 | 服務層級的最高尖峰 IOPS 。 


| "Marax_Expeted_IOPS/IOPS/" | 整數 | 預期 IOPS 上限。 


| "autodge_max-bize" | 整數 | 自動成長的最大百分比。 


| "ONTAP_Aggregg" | –  a| 
列舉的所有資訊。 ONTAP由下列項目組成的支援集合體： ONTAP

* 「叢集 UIID ： ONTAP 叢集 UUID 」
* 「 aggreg_name ： ONTAP fulgregate name 」
* 「 agggr_uuid ： ONTAP fulgregate UUID 」
* 「 node_name ： ONTAP f2 cluster nodename （節點名稱：不完整的叢集節點名稱））》舉例：


[listing]
----
"ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ]
----


| 「 primary Volume 預設值」 | –  a| 
* SnapShot 自動刪除目標可用空間（整數）：此選項指定自動刪除 Snapshot 複本時必須停止的可用空間百分比。
* Auto_Size_mode （字串）： Volume 的自動調整大小模式。允許的值：關、增長、增長、縮減、例如：


[listing]
----
"primary_volume_defaults": {    "snapshot_auto_delete_target_free_space": 3,    "auto_size_mode": "grow_shrink"
----
|===


== 擷取服務層級

使用下表所列的方法擷取所有服務層級。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《 Get 》（取得） | /v2.1 / 服務層級 | 擷取所有服務層級。 | 無 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 3 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 3,
    "records": [
      {
        "name": "standard",
        "description": "Best suited for general purpose workloads",
        "slo": "1000IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 40960,
        "min_iops": 100,
        "peak_iops_per_tb": 1000,
        "expected_iops_per_tb": 700,
        "max_peak_iops": 40000,
        "max_expected_iops": 28000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 875
      },
      {
        "name": "extreme",
        "description": "Best suited for performance-critical workloads",
        "slo": "12000IOPS/TB",
        "min_size": 91625968981,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 500,
        "peak_iops_per_tb": 12000,
        "expected_iops_per_tb": 8000,
        "max_peak_iops": 120000,
        "max_expected_iops": 60000,
        "max_peak_throughput": 3750,
        "max_expected_throughput": 1875
      },
      {
        "name": "premium",
        "description": "Best suited for databases and high performance workloads",
        "slo": "4000IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 300,
        "peak_iops_per_tb": 4000,
        "expected_iops_per_tb": 3000,
        "max_peak_iops": 40000,
        "max_expected_iops": 30000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 937
      }
    ]
  }
}
....


== 依名稱擷取服務層級

使用下表所列的方法、依名稱擷取服務層級。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《 Get 》（取得） | 「 v2.1 / 服務層級 / ｛ name ｝ 」 | 依名稱擷取服務層級。 | 名稱（字串）：服務層級的名稱。 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "name": "premium",
        "description": "Best suited for databases and high performance workloads",
        "slo": "4096IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 300,
        "peak_iops_per_tb": 4096,
        "expected_iops_per_tb": 3000,
        "max_peak_iops": 40000,
        "max_expected_iops": 30000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 937
      }
    ]
  }
}
....


== 建立服務層級

使用下表所列的方法建立服務層級。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 貼文 | /v2.1 / 服務層級 | 建立服務層級。 | 無 
|===
必要的要求內容屬性：「 name 」、「 policy_name 」

* 索取本文範例： *

....
{
  "name": "MyServiceLevelName",
  "description": "My new service level description",
  "policy_name": "nse_value",
  "available": true,
  "grandfathered": false,
  "peak_iops_per_tb": 1000,
  "expected_iops_per_tb": 700,
  "absolute_min_iops": 100,
  "peak_iops_allocation": "allocated_space",
  "io_block_size_kb": 32,
  "min_size_gb": 10,
  "max_size_gb": 40960,
  "max_peak_iops": 20000,
  "max_expected_iops": 5000,
  "autogrow_max_percent": 3,
  "ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ],
  "primary_volume_defaults": {
    "snapshot_auto_delete_target_free_space": 3,
    "auto_size_mode": "grow_shrink"
  }
}
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "name": "MyServiceLevelName",
        "description": "My new service level description",
        "slo": "1000IOPS/TB",
        "min_size": 0,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 40960,
        "min_iops": 100,
        "peak_iops_per_tb": 1000,
        "expected_iops_per_tb": 700,
        "max_peak_iops": 20000,
        "max_expected_iops": 5000,
        "max_peak_throughput": 625,
        "max_expected_throughput": 156
      }
    ]
  }
}
....


== 修改服務層級

使用下表所列的方法來修改服務層級。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《投入》 | 「 v2.1 / 服務層級 / ｛ name ｝ 」 | 修改服務層級的詳細資料。 | 名稱（字串）：服務層級的名稱。 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
{
  "name": "MyNewServiceLevelName",
  "description": "Service level description",
  "policy_name": "nse_value",
  "available": false,
  "grandfathered": false,
  "peak_iops_per_tb": 1000,
  "expected_iops_per_tb": 700,
  "absolute_min_iops": 100,
  "peak_iops_allocation": "allocated_space",
  "io_block_size_kb": 32,
  "min_size_gb": 10,
  "max_size_gb": 40960,
  "max_peak_iops": 20000,
  "max_expected_iops": 5000,
  "autogrow_max_percent": 3,
  "ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ],
  "primary_volume_defaults": {
    "snapshot_auto_delete_target_free_space": 3,
    "auto_size_mode": "grow_shrink"
  }
}
....
* 回應本文範例： *

....
TBA
....


== 依 ID 刪除服務層級

使用下表所列的方法、依 ID 刪除服務層級。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| " 刪除 " | 「 v2.1 / 服務層級 / ｛ name ｝ 」 | 刪除 ID 所識別的服務層級。 | 名稱（字串）：服務層級的名稱。 
|===
* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
No content for succesful delete
....