---
sidebar: sidebar 
permalink: seapiref_subtenants.html 
keywords: netapp, keystone, subtenants, 
summary: Keystone 子租戶 
---
= 子租戶
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用下表所列的方法擷取、建立、修改及刪除子租戶。

|===
| HTTP 方法 | 路徑 | 說明 


| 《 Get 》（取得） | 《 v2.1 / 子租戶》 | 擷取子租戶。 


| 《 Get 》（取得） | 「 v2.1 / 子租戶 / ｛ id ｝ 」 | 依子租戶 ID 擷取子租戶。 


| 貼文 | 《 v2.1 / 子租戶》（ Sub租 戶） | 建立新的子租戶。 


| 《投入》 | 「 v2.1 / 子租戶 / ｛ id ｝ 」 | 修改子租戶的詳細資料。您可以修改子租戶的名稱。 


| " 刪除 " | 「 v2.1 / 子租戶 / ｛ id ｝ 」 | 刪除子租戶。 
|===


=== 子租戶屬性

下表列出子租戶屬性。

|===
| 屬性 | 類型 | 說明 


| "id" | 字串 | 子租戶的唯一識別碼。 


| 名稱 | 字串 | 子租戶名稱。 


| 代碼 | 字串 | 代表子租戶的客戶指定（或預設）代碼。 


| 租戶 ID | 字串 | 子租戶所屬租戶的識別碼。 
|===


=== 擷取所有子租戶

使用下表所列的方法擷取所有子租戶或所有子租戶的子集。指定「租戶 ID 」只會傳回屬於該租戶的子租戶。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《 Get 》（取得） | 《 v2.1 / 子租戶》 | 擷取子租戶。 | 「租戶 ID 」：（選用）歸還屬於指定租戶的子租戶。偏移和限制–請參閱 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 2 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 2,
    "total_records": 202,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 2,
    "records": [      {
        "id": "5e7c3af8aab46c00014ce878",
        "description": "",
        "name": "MySubtenant",
        "code": "mysubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      },
      {
        "id": "5d9144f3869caefed0f39f82",
        "description": "",
        "name": "Mysubtenant2",
        "code": "myothersubtenant",
        "tenant_id": "5d914499869caefed0f39eee",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


=== 依 ID 擷取子租戶

使用下列方法依 ID 擷取子租戶。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《 Get 》（取得） | 「 v2.1 / 子租戶 / ｛ id ｝ 」 | 擷取 ID 指定的子租戶。 | 「 ID （字串）」：子租戶的唯一識別碼。 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e7c3af8aab46c00014ce878",
        "description": "",
        "name": "MySubtenant",
        "code": "subtenantcode",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


=== 建立子租戶

使用下表所列的方法來建立子租戶。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 貼文 | 《 v2.1 / 子租戶》 | 建立新的子租戶。 | 無 
|===
必要的要求內容屬性：「 name 」、「 Code 」、「租戶 ID 」

* 索取本文範例： *

....
{
  "name": "MySubtenant",
  "code": "mynewsubtenant",
  "tenant_id": "5ed5ac802c356a0001a735af"
}
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecefbbef418b40001f20bd6",
        "description": "",
        "name": "MyNewSubtenant",
        "code": "mynewsubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


=== 依 ID 修改子租戶

使用下表所列的方法、依 ID 修改子租戶。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《投入》 | 「 v2.1 / 子租戶 / ｛ id ｝ 」 | 修改 ID 所指定的子租戶。您可以變更子租戶名稱。 | 「 ID （字串）」：子租戶的唯一識別碼。 
|===
必要的要求內容屬性：「 name 」

* 索取本文範例： *

....
{
  "name": "MyModifiedSubtenant"
}
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecefbbef418b40001f20bd6",
        "description": "",
        "name": "MyNewSubtenant",
        "code": "mynewsubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


=== 依 ID 刪除子租戶

使用下表所列的方法、依 ID 刪除子租戶。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| " 刪除 " | 「 v2.1 / 子租戶 / ｛ id ｝ 」 | 刪除 ID 指定的子租戶。 | 「 ID （字串）」：子租戶的唯一識別碼。 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
No content for succesful delete
....