---
sidebar: sidebar 
permalink: seapiref_service_requests.html 
keywords: netapp, keystone, service, requests, 
summary: Keystone 服務要求 
---
= 服務要求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用下表所列的方法來建立及擷取服務要求。

|===


| HTTP 方法 | 路徑 | 說明 


| 《 Get 》（取得） | /v2.1 / 租戶 / ｛ 租戶 ID ｝ / 服務資源等量 | 擷取服務要求。 


| 《 Get 》（取得） | /v2.1 / 租戶 / ｛ 租戶 ID ｝ / 服務者資源 / ｛ id ｝ | 依 ID 擷取服務要求。 


| 貼文 | /v2.1 / 租戶 / ｛ 租戶 ID ｝ / 服務資源資源 / | 建立服務要求。 


| 《 Get 》（取得） | /v2.1 / 租戶 / ｛ 租戶 ID ｝ / 服務資源 / 類別 | 擷取服務要求類別。 
|===


== 服務要求屬性

下表列出服務要求屬性。

|===


| 屬性 | 類型 | 說明 


| 《 ID 》 | 字串 | 服務要求的識別碼。例如：「 s S23 0035952014 。 


| 《 Subject 》（主題） | 字串 | 服務要求的主旨。 


| " 評論 " | 字串 | 對服務要求的意見 


| " 類別 " | 字串 | 申請類別：備份、災難恢復、技術、其他或訂購。 


| " 優先 " | 字串 | 服務要求的優先順序：非常低、低、正常、高或緊急。 


| 「訂閱」 | 字串 | 所學專業：金融學 


| 《承諾》 | –  a| 
訂購承諾詳細資料、包括：

* 服務層級（字串）：服務層級：標準、優質或極致。
* new_承諾 （整數）：需要新的總容量。




| 區域 | 字串 | 區域名稱。 


| 《 Subenter_id 》 | 字串 | 子租戶識別碼。 


| 《 torage_object_type] 》 | 字串 | 儲存物件類型：檔案伺服器或區塊存放區。 


| 《 torage_object_id 》 | 字串 | 儲存物件的識別碼。例如：「 5d2fb0fb4f47df00015274e3 」 


| ' 服務類型 ' | 字串 | 服務類型：檔案服務、區塊儲存或物件儲存。 
|===


== 擷取服務要求

使用下表所列的方法擷取指定租戶的服務要求類別。

|===


| HTTP 方法 | 路徑 | 說明 | 參數 


| 《 Get 》（獲取） | /v2.1 / 租戶 / ｛ 租戶 ID ｝ / 服務資源等量 | 擷取服務要求。 | 「租戶 ID 」：（選用）傳回指定租戶的服務要求。「偏移」和「限制」、請參閱 link:seapiref_netapp_service_engine_rest_apis.html#pagination>["常見分頁"] 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 34,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 6,
    "limit": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....


== 依 ID 擷取服務要求

使用下表所列的方法、依服務要求 ID 擷取服務要求。

|===


| HTTP 方法 | 路徑 | 說明 | 參數 


| 《 Get 》（取得） | /v2.1 / 租戶 / ｛ 租戶 ID ｝ / 服務者資源 / ｛ id ｝ | 依 ID 擷取服務要求。  a| 
* 「租戶 ID 」：租戶 ID
* 「 id 」：服務要求 ID 例如： SRQ0035952014


|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....


== 建立服務要求

使用下表所列的方法來建立服務要求。

|===


| HTTP 方法 | 路徑 | 說明 | 參數 


| 貼文 | /v2.1 / 租戶 / ｛ 租戶 ID ｝ / 服務資源 / 類別 | 建立服務要求。 | `tenant_id`：租戶識別碼。 
|===
必要的要求內容屬性：所需的屬性取決於服務要求的類別。下表列出要求內容屬性。

|===


| 類別 | 必要 


| 訂購 | `subscription` 和 `commitment` 


| 災難恢復 | `storage_object_type`、 `subtenant_id`和 `storage_object_id` 


| 技術 | `subtenant_id` 和 `service_type`如果 `service_type` 是檔案服務或區塊儲存、需要區域。 


| 其他 | 區域 
|===
* 索取本文範例： *

....
{
  "subject": "string",
  "comment": "string",
  "category": "subscription",
  "priority": "Normal",
  "subscription": "A-S00003969",
  "commitment": {
    "service_level": "standard",
    "new_commitment": 10
  },
  "zone": "au-east1-a",
  "subtenant_id": "5d2fb0fb4f47df00015274e3",
  "storage_object_type": "fileserver",
  "storage_object_id": "5d2fb0fb4f47df00015274e3",
  "service_type": "File Services"
}
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "string",
        "subject": "string",
        "description": "string",
        "status": "New",
        "priority": "Normal",
        "createdDate": "2020-05-12T03:18:25+0000",
        "UpdatedDate": "2020-05-12T03:18:25+0000"
      }
    ]
  }
....


== 擷取服務要求類別

下表列出指定租戶的擷取服務要求類別。

|===


| HTTP 方法 | 路徑 | 說明 | 參數 


| 《 Get 》（取得） | /v2.1 / 租戶 / ｛ 租戶 ID ｝ / 服務資源 / 類別 | 擷取服務要求類別。 | `tenant_id:` （選用）傳回指定租戶的服務要求。 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 5 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 5,
    "records": [
      {
        "key": "dr",
        "value": "Disaster Recovery Failover"
      },
      {
        "key": "technical",
        "value": "Technical Issue"
      },
      {
        "key": "other",
        "value": "Other"
      },
      {
        "key": "subscription",
        "value": "Subscription Management"
      },
      {
        "key": "backup",
        "value": "Backup Restore"
      }
    ]
  }
}
....