---
sidebar: sidebar 
permalink: seapiref_storagegrid_instances.html 
keywords: netapp, keystone, storagegrid, instances, 
summary: Keystone StorageGRID 執行個體 
---
= 執行個體 StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用下表所列的方法來設定及管理 StorageGRID 支援物件儲存的各種實例。

|===
| HTTP 方法 | 路徑 | 說明 


| 《 Get 》（取得） | /v2.1 / storagegridinstances ） | 擷 StorageGRID 取實體執行個體。 


| 貼文 | /v2.1 / storagegridinstances ） | 建立新 StorageGRID 的物件儲存執行個體來裝載物件儲存。 


| 《 Get 》（取得） | /v2.1 / storagegridinstances/｛ id ｝ | 依 ID 擷取 StorageGRID 實體執行個體。 


| 《投入》 | /v2.1 / storagegridinstances/｛ id ｝ | 更新 StorageGRID 執行個體。 
|===


=== 執行個體屬性 StorageGRID

下表列出 StorageGRID 了一些不執行個體屬性。

|===
| 屬性 | 類型 | 說明 


| "id" | 字串 | 用於執行個體的唯一識別碼 StorageGRID 。 


| 名稱 | 字串 | 執行個體名稱。 StorageGRID 


| 「 admin_ress_uri 」 | 字串（ $Uri ） | 這個節點端點是由整個系統管理的。 StorageGRID 


| s 3_End端 點 | 字串（ $Uri ） | 無縫端點。 StorageGRID例如： ["https://s3.examplegrid.com"[]、 "https://s3.location.company.com"`[] ] 


| 《 GRID_USERNAME 》 | 字串 | 這個使用者名稱。 StorageGRID 


| "GRID_PASSON" | 字串 | 這個密碼。 StorageGRID 


| ' 租戶 _ 使用者名稱 ' | 字串 | 系統管理員使用者名稱。 StorageGRID 


| 租戶密碼 | 字串 | 系統管理員密碼。 StorageGRID 


| 「 Subscale_number」 | 字串 | 所學專業：金融學 
|===


=== 擷 StorageGRID 取實體執行個體

使用下表所列的方法來擷取 StorageGRID 列舉的實例。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《 Get 》（取得） | /v2.1 / storagegridinstances ） | 擷 StorageGRID 取實體執行個體。 | 無 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e3ba2840271823644cb8ab6",
        "name": "NSE StorageGRID Dev1",
        "user_id": "5bbee380a2df7a04d43acaee",
        "admin_rest_uri": "https://sggmi-dev.dev.ausngs.netapp.au",
        "s3_endpoints": [
          "https://sgs3.dev.ausngs.netapp.au"
        ],
        "subscription_number": "A-S00004566"
      }
    ]
  }
}
....


=== 根據 ID 擷取 StorageGRID 實體執行個體

請使用下表所列的方法、 StorageGRID 依 ID 擷取不檢索。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《 Get 》（取得） | /v2.1 / storagegridinstances/｛ id ｝ | 依 ID 擷取 StorageGRID 實體執行個體。 | 「 id （字串）」： StorageGRID 此為實例的唯一識別碼。 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e3ba2840271823644cb8ab6",
        "name": "NSE StorageGRID Dev1",
        "user_id": "5bbee380a2df7a04d43acaee",
        "admin_rest_uri": "https://sggmi-dev.dev.ausngs.netapp.au",
        "s3_endpoints": [
          "https://sgs3.dev.ausngs.netapp.au"
        ],
        "subscription_number": "A-S00004566"
      }
    ]
  }
}
....


=== 根據 ID 建立 StorageGRID 一個實例

使用下表所列的方法、 StorageGRID 根據 ID 建立一個實例。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《貼文》 | /v2.1 / storagegridinstances/｛ id ｝ | 依 ID 擷取 StorageGRID 實體執行個體。 | 「 ID （字串）：」 StorageGRID 這是一個獨特的例子。 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
{
  "name": "Grid1",
  "admin_rest_uri": "https://examplegrid.com",
  "s3_endpoints": [
    "https://s3.examplegrid.com",
    "https://s3.location.company.com"
  ],
  "grid_username": "root",
  "grid_password": "string",
  "tenant_username": "root",
  "tenant_password": "string",
  "subscription_number": "A-S00003969"
}
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5d2fb0fb4f47df00015274e3",
        "name": "Grid1",
        "admin_rest_uri": "https://examplegrid.com",
        "user_id": "5d2fb0fb4f47df00015274e3",
        "s3_endpoints": [
          "https://s3.examplegrid.com",
          "https://s3.location.company.com"
        ],
        "subscription_number": "A-S00003969"
      }
    ]
  }
}
....


=== 根據 ID 修改 StorageGRID 執行個體

使用下表所列的方法、 StorageGRID 依 ID 修改一個實例。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《投入》 | /v2.1 / storagegridinstances/｛ id ｝ | 根據 ID 修改 StorageGRID 執行個體。 | 「 id （字串）」： StorageGRID 此為實例的唯一識別碼。 
|===
必要的 Request 本文屬性：「無」

* 索取本文範例： *

....
{
  "name": "Grid1",
  "admin_rest_uri": "https://examplegrid.com",
  "s3_endpoints": [
    "https://s3.examplegrid.com",
    "https://s3.location.company.com"
  ],
  "grid_username": "root",
  "grid_password": "string",
  "tenant_username": "root",
  "tenant_password": "string",
  "subscription_number": "A-S00003969"
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5d2fb0fb4f47df00015274e3",
        "name": "Grid1",
        "admin_rest_uri": "https://examplegrid.com",
        "user_id": "5d2fb0fb4f47df00015274e3",
        "s3_endpoints": [
          "https://s3.examplegrid.com",
          "https://s3.location.company.com"
        ],
        "subscription_number": "A-S00003969"
      }
    ]
  }
}
....