---
sidebar: sidebar 
permalink: seapiref_file_services_apis.html 
keywords: netapp, keystone, file services, file servers, file shares, apis 
summary: Keystone 檔案服務 API 
---
= 檔案服務 API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用檔案服務 API 來檢視及管理檔案伺服器和檔案共用。

在建立檔案共用之前、您必須先建立檔案伺服器來裝載它們。



== 檔案伺服器 API

您可以使用檔案伺服器 API 來檢視及管理檔案伺服器。如需檔案伺服器的詳細資訊、請參閱 link:hsewebiug_create_a_file_server.html["建立檔案伺服器"]。

[cols="1,1,3,2"]
|===
| HTTP Verb | 路徑 | 說明 | 必要參數 / 要求本文 


 a| 
《 Get 》（取得）
 a| 
/`v2.1 / 檔案伺服器 '
| 您可以擷取所有檔案伺服器的詳細資料。擷取檔案伺服器的詳細資料、例如檔案伺服器 ID 、名稱、區域、區域、租戶、 和標記。  a| 
「偏移」：開始收集結果集之前要跳過的項目數。「限制」：要退回的項目數量。



 a| 
《 Get 》（取得）
 a| 
/`v2.1 / 檔案伺服器 /{id}
| 您可以擷取特定檔案伺服器的詳細資料。擷取檔案伺服器的詳細資料、例如名稱、區域、區域、租戶、 和標記、以輸入的 ID 為基礎。  a| 
「 id 」：檔案伺服器的 ID 。



 a| 
貼文
 a| 
/`v2.1 / 檔案伺服器 '
| 您可以建立檔案伺服器。新增要求本文中的值、以建立具有指定參數的檔案伺服器、例如名稱、子租戶 ID 、區域、子網路 ID 。  a| 
「名稱」：檔案伺服器的名稱。「 ubenter_id 」：子租戶的 ID 。「區域」：區域名稱。「 ubnet_id 」：子網路的 ID 。



 a| 
貼文
 a| 
/v2.1 / 檔案伺服器 /{id}/' 「標記」
| 您可以為檔案伺服器建立或取代標記。將檔案伺服器的 ID 和標記值新增至要求本文中的「 key:value 配對」格式。  a| 
「 id 」：檔案伺服器的 ID 。



 a| 
《投入》
 a| 
/`v2.1 / 檔案伺服器 /{id}
| 您可以根據檔案伺服器的 ID 來修改任何檔案伺服器。新增檔案伺服器的 ID 、以及您要在要求本文中修改的值、例如名稱、傳輸協定、區域、區域和標記。  a| 
「 id 」：檔案伺服器的 ID 。



 a| 
" 刪除 "
 a| 
/`v2.1 / 檔案伺服器 /{id}
 a| 
您可以依檔案伺服器 ID 刪除任何檔案伺服器。
 a| 
「 id 」：檔案伺服器的 ID 。

|===
[NOTE]
====
刪除檔案伺服器之前、您應該先刪除對應至該伺服器的所有檔案共用。

刪除啟用 CIFS 的檔案伺服器之後、 Active Directory 電腦物件仍會保留。要求 Active Directory 管理員從 Active Directory 手動移除已刪除檔案伺服器的電腦物件。

====


== 檔案共用 API

您可以使用檔案共用 API 來檢視及管理檔案共用。如需檔案共用的詳細資訊、請參閱 link:sewebiug_create_a_new_file_share.html["建立檔案共用區"]。

[cols="1,1,3,2"]
|===
| HTTP Verb | 路徑 | 說明 | 必要參數 / 要求本文 


 a| 
《 Get 》（取得）
 a| 
/`v2.1 / 檔案資源 '
| 您可以擷取所有檔案共用的詳細資料。擷取檔案共用的詳細資料、例如 ID 、名稱、快照原則、傳輸協定、 檔案伺服器 IP 和標記。  a| 
「偏移」：開始收集結果集之前要跳過的項目數。「限制」：要退回的項目數量。



 a| 
《 Get 》（取得）
 a| 
/`v2.1 / 檔案資源 / ｛ id ｝ '
| 您可以擷取特定檔案共用區的詳細資料。擷取檔案共用的詳細資料、例如 ID 、名稱、快照原則、傳輸協定、檔案伺服器 IP 、 和標記、以輸入的 ID 為基礎。  a| 
「 id 」：檔案共用區的 ID 。



 a| 
貼文
 a| 
/`v2.1 / 檔案資源 '
| 您可以建立檔案共用區。新增要求本文中的值、以建立具有指定參數的檔案共用區、例如 ID 、名稱、快照原則、傳輸協定、 檔案伺服器 IP 和標記。  a| 
「名稱」：檔案共用區的名稱。「 hare 路徑」：檔案共用區的路徑。「 fileserver_id 」：檔案伺服器的 ID 。「 ize_GB 」：檔案共用區大小（以 GB 為單位）。「 service_level 」：適用的服務層級名稱： Standard 、 Premium 、 Premium 分層、 Extreme 或 Extreme 分層。「傳輸協定」：用來存取檔案共用區（ NFS 、 CIFS 或多傳輸協定）的傳輸協定。「 ecurity_style 」：安全風格（ Unix 或 NTFS ）。「匯出原則」：檔案共用區的匯出原則。



 a| 
貼文
 a| 
/v2.1 / 檔案資源 / ｛ id ｝ / ' 「快照 / ｛ name ｝ 」
| 您可以建立檔案共用區的快照。  a| 
「 id 」：檔案共用區的 ID 。「名稱」：快照的名稱。



 a| 
貼文
 a| 
/v2.1 / 檔案資源 / ｛ id ｝ / ' 標記 '
| 您可以建立或取代檔案共用的標記。在要求本文中、以「 key:value 配對」格式新增檔案共用的 ID 和標記值。  a| 
「 id 」：檔案共用區的 ID 。



 a| 
《投入》
 a| 
/`v2.1 / 檔案資源 / ｛ id ｝ '
| 您可以根據檔案共用的 ID 來修改任何檔案共用。在要求本文中新增檔案伺服器的 ID 和您要修改的值、例如名稱、傳輸協定、快照原則、備份原則和標記。  a| 
「 id 」：檔案共用區的 ID 。「名稱」：檔案共用區的名稱。「 ize_GB 」：檔案共用區大小（以 GB 為單位）。「 service_level 」：適用的服務層級名稱： Standard 、 Premium 、 Premium 分層、 Extreme 或 Extreme 分層。「傳輸協定」：用來存取檔案共用區（ NFS 、 CIFS 或多傳輸協定）的傳輸協定。「匯出原則」：檔案共用區的匯出原則。



 a| 
" 刪除 "
 a| 
/`v2.1 / 檔案資源 / ｛ id ｝ '
| 您可以依其 ID 刪除任何檔案共用。  a| 
「 id 」：檔案共用區的 ID 。



 a| 
" 刪除 "
 a| 
/v2.1 / 檔案資源 / ｛ id ｝ / ' 「快照 / ｛ name ｝ 」
| 您可以依照檔案共用區的 ID 和快照名稱來刪除檔案共用區的任何快照。  a| 
「 id 」：檔案共用區的 ID 。「名稱」：快照的名稱。

|===

NOTE: 如果是 CIFS 共用、在共用路徑結尾加上「 $ 」字元、就會使其成為隱藏的共用區、例如「 pathtomyhiddenshare$ 」。
