---
sidebar: sidebar 
permalink: seapiref_backups_apis.html 
keywords: netapp, keystone, backups, apis, 
summary: Keystone 備份 API 
---
= 備份 API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用備份API來檢視及管理環境中磁碟區（檔案共用和磁碟）的備份或還原點。

[cols="1,1,3,2"]
|===
| HTTP Verb | 路徑 | 說明 | 必要參數 / 要求本文 


 a| 
《 Get 》（取得）
 a| 
/v2.1 / 備份
| 您可以擷取租戶下為子租戶所建立之所有磁碟區的所有備份物件詳細資料。擷取來源磁碟區和備份物件的詳細資料、例如備份原則、區域和標記。  a| 
「偏移」：開始收集結果集之前要跳過的項目數。「限制」：要退回的項目數量。



 a| 
《 Get 》（取得）
 a| 
/v2.1 / 備份 /{id}
| 您可以在租戶下擷取針對子租戶所建立之磁碟區的特定備份物件詳細資料。根據輸入的 ID 擷取來源 Volume 和備份物件的詳細資料、例如備份原則、區域和標記。  a| 
「 id 」：備份物件的 ID 。



 a| 
《 Get 》（取得）
 a| 
/v2.1 / 備份 / ｛ id ｝ / ' 「 restore_points 」
| 您可以擷取特定備份物件的所有恢復點詳細資料。系統會擷取詳細資料、例如時間戳記和名稱。  a| 
「 id 」：備份物件的 ID 。



 a| 
《 Get 》（取得）
 a| 
/v2.1 / 備份 / ｛ id ｝ / ' 「 restore_points/ ｛ name ｝ 」
| 您可以擷取特定備份物件的任何還原點詳細資料。系統會擷取詳細資料、例如時間戳記和名稱。  a| 
「 id 」：備份物件的 ID 。「名稱」：恢復點的名稱。



 a| 
貼文
 a| 
/v2.1 / 備份
| 您可以為特定來源 Volume 建立備份物件。新增要求本文中的值、以建立具有指定參數的備份物件、例如備份原則、要保留的備份複本數目、以及來源資源 ID 。  a| 
「」、「 SOURC_RESTON_RESTAILANE_type" ：「 < 資源類型 > 」、「 SOURCER_RESERE_id 」：「 <ID>" 、「備份區域 > 」、「備份原則」： ｛ 「每日備份次數」、「每週備份次數」： < 每週備份數、「每次備份數」「每次備份數」、「每次備份數」「每次備份數」「每次備份數」、按鍵備份數」、按鍵 1 、按鍵備份數： < 每次備份數： < 每次備份數、按鍵備份數： < 每次備份數、按鍵備份數： < 每次備份數 2 、按鍵備份數 2 、按「每月次數」、按鍵備份數： "<Tag N>" } ’



 a| 
貼文
 a| 
/v2.1 / 備份 / ｛ id ｝ / 標記
| 您可以為子租戶建立或取代備份物件的標記。將備份物件的 ID 和標記值新增至要求本文中的「 key:value 配對」格式。  a| 
「 id 」：備份物件的 ID 。'' ｛ "key1" ： "<Tag1>" 、 "key2" ： "<Tag2>" 、 "keyN" ： "<TagN>" } '



 a| 
《修補程式》
 a| 
/v2.1 / 備份 /{id}
 a| 
您可以根據磁碟區的 ID 來修改任何備份物件。在要求本文中新增備份物件的 ID 和您要修改的值、例如備份原則詳細資料、要保留的備份數、以及來源資源 ID 。

[NOTE]
====
您可以將「修補程式」要求中的「資源資源 ID 」參數值設為 null 、使備份物件孤立。這會移除 SnapMirror 關係、但保留備份磁碟區及其下的還原點。

==== a| 
「 id 」：備份物件的 ID 。「」、「 backup_policy 」： ｛ "diting_resource_id" ：「 <Resource ID>" 、「 backup_policy 」： ｛ "diting_backups_to_keee" ： < 每日備份數 > 、「每週備份數」、「每月備份數」： < 每月備份數 > 、「 ad_keyn' 、 < 按鍵備份數『 2 、按鍵備份數』、 < 按鍵備份數『 2 、按鍵備份數』、按鍵備份數』、按鍵備份數『 < 按鍵備份數』、 < 按鍵備份數『 2 ： ' 、 < 按鍵備份數』「 < 按鍵備份數』、 < 按鍵備份數』、按鍵備份數『 2



 a| 
" 刪除 "
 a| 
/v2.1 / 備份 /{id}
| 您可以刪除磁碟區的任何備份物件及所有恢復點。  a| 
「 id 」：備份物件的 ID 。



 a| 
" 刪除 "
 a| 
/v2.1 / 備份 / ｛ id ｝ / ' 「 restore_points/ ｛ name ｝ 」
| 您可以刪除磁碟區特定備份物件中的任何還原點。  a| 
「 id 」：備份物件的 ID 。「名稱」：恢復點的名稱。

|===