---
sidebar: sidebar 
permalink: seapiref_ontap_clusters.html 
keywords:  
summary:  
---
= 叢集 ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用下表所列的方法來擷取 ONTAP 、建立、修改及刪除等叢集。

|===
| HTTP 方法 | 路徑 | 說明 


| 《 Get 》（取得） | /v2.1 / ontap叢 集 | 擷取所有 ONTAP 的叢集。 


| 《 Get 》（取得） | /v2.1 / ontap叢 集 / ｛ id ｝ | 根據 ID 擷取 ONTAP 一個叢集。 


| 貼文 | /v2.1 / ontap叢 集 | 建立新 ONTAP 的叢集。 


| 《投入》 | /v2.1 / ontap叢 集 / ｛ id ｝ | 依 ONTAP ID 更新叢集庫存。 


| " 刪除 " | /v2.1 / ontap叢 集 / ｛ id ｝ | 刪除 ONTAP 一個叢集。 
|===


=== 叢集屬性 ONTAP

下表列出 ONTAP 了叢集的功能特性。

|===
| 屬性 | 類型 | 說明 


| "id" | 字串 | 這個獨特的 ONTAP 叢集識別碼。 


| 名稱 | 字串 | 此為整個叢集的名稱。 ONTAP 


| 《 uuid 》 | 字串 | 此為支援叢集的通用唯一識別碼（ UUID ） ONTAP 。 


| "Maranagement _IP" （管理 IP ） | 字串 | 支援叢集管理的 IPv6 位址。 ONTAP 


| 《使用者名稱》 | 字串 | 此為整個叢集的名稱 ONTAP 


| 密碼 | 字串 | 此為叢集密碼 ONTAP 


| "Provisioning 狀況 " | 字串  a| 
識別叢集是否可用於資源配置作業。選項包括：

* 開啟
* 已關閉




| "data_network_ip_CIDR | 字串 | 子網路的 CIDR 表示法。 


| "data_network_default_gateway" | 字串 | 此為 IPV4 位址。 


| "DAATA 網路連接埠 " | –  a| 
一份關於叢集資料網路連接埠的清單 ONTAP 。

[listing]
----
For example:
[
  {
  "node_name": "dev-ots-per01-01",
  "port_name": "e0c-120",
  "parent_port": "e0c"
  }
]
----


| 《叢集間生命》 | –  a| 
叢集間叢集生命體。 ONTAP

[listing]
----
For example:
[
  {
  "name": "peer1",
  "node": "aff-01",
  "port": "a0a-103",
  "address": "10.128.113.232",
  "netmask": "255.255.255.0"
  },
{
  "name": "peer2",
  "node": "aff-02",
  "port": "a0a-103",
  "address": "10.128.113.233",
  "netmask": "255.255.255.0"
  }
]
----


| 《 VM_root_service_level 》 | 字串 | 叢集儲存虛擬機器（ SVM ）根服務層級名稱。 ONTAP適用的值包括「標準」、「極致」或「優質」。此服務層級預設指派給叢集下建立的所有 SVM 。叢集應具有所述服務層級的相關 Aggregate 。 


| 區域 | 字串 | 區域名稱。 


| 「 Subscale_number」 | 字串 | 所學專業：電子商務 


| 「服務 _ 可用」 | –  a| 
可用服務及其狀態的清單。例如：

[listing]
----
{
  "fcp": false,
  "iscsi": true,
  "nas": true
  }
----


| "data_FCP 連接埠 " | –  a| 
節點和連接埠清單、適用於啟用 FCP ONTAP 的功能性功能的叢集。例如：

[listing]
----
[  {   "node_name": "aff-01",   "port_name": "0g"  },  {   "node_name": "aff-01",   "port_name": "0h"
  ]
----


| 《是管理委員會》 | 布林值 | 指出叢集是否 MetroCluster 啟用了不支援的功能。預設值為「假」。 


| "M_PARTNER_叢 集 " | 字串 | 目前叢集 MetroCluster 的合作夥伴叢集在一個雙組中的識別碼。如果叢集已啟用 MetroCluster 以供使用、則為必要項目。 
|===


=== 擷取所有 ONTAP 的叢集

使用下列方法擷取所有 ONTAP 的叢集或 ONTAP 部分的叢集。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《 Get 》（取得） | /v2.1 / ontap叢 集 | 擷取所有 ONTAP 的叢集。 | 「偏移」和「限制」–請參閱 link:seapiref_netapp_service_engine_rest_apis.html#pagination>["常見分頁"] 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 2 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 2,
    "total_records": 5,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 3,
    "limit": 2,
    "records": [
      {
        "id": "5c5bb9f16680a7002a5f7450",
        "name": "dev-ots-per01",
        "region": "au-west1",
        "zone": "au-west1-a",
        "uuid": "63053baa-ada4-11ea-b197-005056a4c0ef",
        "management_ip": "10.128.115.173",
        "username": "admin",
        "services_available": {
          "fcp": false,
          "iscsi": true,
          "nas": true
        },
        "provisioning_state": "open",
        "data_network_ports": [
          {
            "node_name": "dev-ots-per01-01",
            "port_name": "e0c-120",
            "parent_port": "e0c"
          }
        ],
        "data_network_ip_cidr": "10.96.120.0/24",
        "data_network_default_gateway": "10.96.120.1",
        "svm_root_service_level": "performance",
        "intercluster_lifs": [
          {
            "name": "dev-ots-per01-01-icl01",
            "node": "dev-ots-per01-01",
            "port": "e0b",
            "address": "10.128.115.144",
            "netmask": "255.255.255.0"
          }
        ],
        "subscription_number": "A-S00003875",
        "created": "2019-02-22T03:38:38.867Z",
        "data_fcp_ports": []
      },
      {
        "id": "5eaf5249f038943eb46b6608",
        "name": "aff",
        "region": "au-east1",
        "zone": "au-east1-b",
        "uuid": "62d649d2-07a1-11e6-9549-00a0985c0dcb",
        "management_ip": "10.128.113.69",
        "username": "admin",
        "services_available": {
          "fcp": true,
          "iscsi": true,
          "nas": true
        },
        "provisioning_state": "open",
        "data_network_ports": [
          {
            "node_name": "aff-01",
            "port_name": "a0a-2000",
            "parent_port": "a0a"
          },
          {
            "node_name": "aff-02",
            "port_name": "a0a-2000",
            "parent_port": "a0a"
          }
        ],
        "data_network_ip_cidr": "10.50.50.0/24",
        "data_network_default_gateway": "10.50.50.1",
        "svm_root_service_level": "premium",
        "intercluster_lifs": [
          {
            "name": "peer1",
            "node": "aff-01",
            "port": "a0a-103",
            "address": "10.128.113.232",
            "netmask": "255.255.255.0"
          },
          {
            "name": "peer2",
            "node": "aff-02",
            "port": "a0a-103",
            "address": "10.128.113.233",
            "netmask": "255.255.255.0"
          }
        ],
        "subscription_number": "A-S00004635",
        "created": "2019-02-22T03:38:38.867Z",
        "data_fcp_ports": [
          {
            "node_name": "aff-01",
            "port_name": "0g"
          },
          {
            "node_name": "aff-01",
            "port_name": "0h"
          },
          {
            "node_name": "aff-02",
            "port_name": "0g"
          },
          {
            "node_name": "aff-02",
            "port_name": "0h"
          }
        ],
        "is_mcc": false,
        "created": "1995-09-07T10:40:52Z"
      }
    ]
  }
}
....


=== 依 ID 擷取 ONTAP 叢集

請使用下列方法 ONTAP 、依 ID 擷取各個叢集。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《 Get 》（取得） | /v2.1 / ontap叢 集 / ｛ id ｝ | 擷取 ONTAP ID 識別的叢集。 | 「 ID （字串）」： ONTAP 叢集的唯一識別碼。 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5c5bb9f16680a7002a5f7450",
        "name": "dev-ots-per01",
        "region": "au-west1",
        "zone": "au-west1-a",
        "uuid": "63053baa-ada4-11ea-b197-005056a4c0ef",
        "management_ip": "10.128.115.173",
        "username": "admin",
        "services_available": {
          "fcp": false,
          "iscsi": true,
          "nas": true
        },
        "provisioning_state": "open",
        "data_network_ports": [
          {
            "node_name": "dev-ots-per01-01",
            "port_name": "e0c-120",
            "parent_port": "e0c"
          }
        ],
        "data_network_ip_cidr": "10.96.120.0/24",
        "data_network_default_gateway": "10.96.120.1",
        "svm_root_service_level": "performance",
        "intercluster_lifs": [
          {
            "name": "dev-ots-per01-01-icl01",
            "node": "dev-ots-per01-01",
            "port": "e0b",
            "address": "10.128.115.144",
            "netmask": "255.255.255.0"
          }
        ],
        "subscription_number": "A-S00003875",
        "created": "2019-02-22T03:38:38.867Z",
        "data_fcp_ports": [],
        "is_mcc": false,
        "created": "1995-09-07T10:40:52Z"
      }
    ]
  }
}
....


=== 建立 ONTAP 叢集

使用下表中的 API 建立 ONTAP 一個不只是一個的叢集。

支援 iSCSI 服務的情況下、一律會建立支援的叢集。 ONTAP或者、如果基礎架構支援 FCP 服務、也可以啟用該服務。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 貼文 | /v2.1 / ontap叢 集 | 建立 ONTAP 一個叢集。 | 無 
|===
必要的要求內容屬性：「 name 」、「 uuid 、 management _ip 」、「 userName 」、「 password 」、 「 data_network_ip_CIDR 」、「 data_network_default_gateway」 、「 intercluster _lifs 」、「區域」

如果啟用 FCP （使用「服務 _ 可用」 FCP 屬性）、則需要「 data_FCP 」連接埠。

如果「 is _MCC 」為真、則需要「 mcc_PARTNER_cluster 」。

* 索取本文範例： *

....
{
  "name": "clustername",
  "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
  "management_ip": "10.128.112.165",
  "username": "admin",
  "password": "ClusterPassword",
  "provisioning_state": "open",
  "data_network_ip_cidr": "10.96.112.0/24",
  "data_network_default_gateway": "10.96.112.1",
  "data_network_ports": [
    {
      "node_name": "clustername-01",
      "port_name": "e0c-112",
      "parent_port": "e0c"
    }
  ],
  "intercluster_lifs": [
    {
      "name": "clustername-01-icl01",
      "node": "clustername-01",
      "port": "e0b",
      "address": "10.128.112.222",
      "netmask": "255.255.255.0"
    }
  ],
  "svm_root_service_level": "extreme",
  "zone": "MyZone",
  "subscription_number": "",
  "services_available": {
    "fcp": false,
    "iscsi": true,
    "nas": true
  },
  "data_fcp_ports": [
  ],
  "is_mcc": false,
}
....
* 回應本文範例： *

....
{
    "status": {
        "user_message": "Okay. New resource created.",
        "verbose_message": "",
        "code": 201
    },
    "result": {
        "returned_records": 1,
        "records": [
            {
                "id": "5ef155b8f5591100010a75c5",
                "name": "clustername",
                "region": "MyRegion",
                "zone": "MyZone",
                "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
                "management_ip": "10.128.112.165",
                "username": "admin",
                "services_available": {
                    "fcp": false,
                    "iscsi": true,
                    "nas": true
                },
                "provisioning_state": "open",
                "data_network_ports": [
                    {
                        "node_name": "clustername-01",
                        "port_name": "e0c-112",
                        "parent_port": "e0c"
                    }
                ],
                "data_network_ip_cidr": "10.96.112.0/24",
                "data_network_default_gateway": "10.96.112.1",
                "svm_root_service_level": "extreme",
                "intercluster_lifs": [
                    {
                        "name": "clustername-01-icl01",
                        "node": "clustername-01",
                        "port": "e0b",
                        "address": "10.128.112.222",
                        "netmask": "255.255.255.0"
                    }
                ],
                "subscription_number": "",
                "created": "2020-06-23T01:07:04.563Z",
                "data_fcp_ports": [],
                "is_mcc": false,
                "mcc_partner_cluster": "5d2fb0fb4f47df00015274e3",
                "created": "1995-09-07T10:40:52Z"
            }
        ]
    }
}
....


=== 修改 ONTAP 叢集

使用下列方法來修改 ONTAP 叢集。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| 《投入》 | /v2.1 / ontap叢 集 / ｛ id ｝ | 修改 ONTAP 由 ID 識別的叢集詳細資料。 | 「 ID （字串）」： ONTAP 叢集的唯一識別碼。 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
{
  "name": "clustername",
  "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
  "management_ip": "10.128.112.165",
  "username": "admin",
  "password": "ClusterPassword",
  "provisioning_state": "open",
  "data_network_ip_cidr": "10.96.112.0/24",
  "data_network_default_gateway": "10.96.112.1",
  "data_network_ports": [
    {
      "node_name": "dev-ots-syd01-01",
      "port_name": "e0c-112",
      "parent_port": "e0c"
    }
  ],
  "intercluster_lifs": [
    {
      "name": "dev-ots-syd01-01-icl01",
      "node": "dev-ots-syd01-01",
      "port": "e0b",
      "address": "10.128.112.222",
      "netmask": "255.255.255.0"
    }
  ],
  "svm_root_service_level": "standard",
  "zone": "MyZone",
  "subscription_number": "",
  "services_available": {
    "fcp": false,
    "iscsi": true,
    "nas": false
  },
  "data_fcp_ports": [
  ]
}
....
* 回應本文範例： *

....
{
    "status": {
        "user_message": "Okay. Accepted for processing.",
        "verbose_message": "",
        "code": 202
    },
    "result": {
        "returned_records": 1,
        "records": [
            {
                "id": "5ef155b8f5591100010a75c5",
                "name": "clustername",
                "region": "MyRegion",
                "zone": "MyZone",
                "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
                "management_ip": "10.128.112.165",
                "username": "admin",
                "services_available": {
                    "fcp": false,
                    "iscsi": true,
                    "nas": true
                },
                "provisioning_state": "open",
                "data_network_ports": [
                    {
                        "node_name": "dev-ots-syd01-01",
                        "port_name": "e0c-112",
                        "parent_port": "e0c"
                    }
                ],
                "data_network_ip_cidr": "10.96.112.0/24",
                "data_network_default_gateway": "10.96.112.1",
                "svm_root_service_level": "standard",
                "intercluster_lifs": [
                    {
                        "name": "dev-ots-syd01-01-icl01",
                        "node": "dev-ots-syd01-01",
                        "port": "e0b",
                        "address": "10.128.112.222",
                        "netmask": "255.255.255.0"
                    }
                ],
                "subscription_number": "",
                "created": "2020-06-23T01:07:04.563Z",
                "data_fcp_ports": [],
                "is_mcc": false,
                "mcc_partner_cluster": "5d2fb0fb4f47df00015274e3",
                "created": "1995-09-07T10:40:52Z"
            }
        ]
    }
}
....


=== 刪除 ONTAP 一個叢集

使用下表所列的方法刪除 ONTAP 一個叢集。

|===
| HTTP 方法 | 路徑 | 說明 | 參數 


| " 刪除 " | /v2.1 / ontap叢 集 / ｛ id ｝ | 刪除 ONTAP ID 所識別的叢集。 | 「 id （字串）」： ONTAP 叢集的唯一識別碼。 
|===
必要的要求內容屬性：「無」

* 索取本文範例： *

....
none
....
* 回應本文範例： *

....
No content for succesful delete
....