---
sidebar: sidebar 
permalink: sewebiug_managing_tenants_and_subtenants.html 
keywords: netapp, keystone, managing, subtenants, 
summary: Keystone 管理子租戶 
---
= 管理租戶和租戶
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用 NetApp 服務引擎來檢視及管理租戶和租戶。初始租賃是由 NetApp 支援服務供應商 / 合作夥伴和租戶所建立。區域、區域和訂閱已由支援部門設定、當您根據租賃建立租戶和子租戶時、就可以使用。



== 租戶

如果您是合作夥伴管理員、可以從 * 管理 * > * 租戶 * 建立、修改及刪除租戶。租戶管理員只能檢視各自的租戶訂閱和子租戶。對於合作夥伴租賃下的租戶、您也可以定義網路。



=== 建立租戶

如果您是合作夥伴管理員、可以建立租戶。您也可以為每個租戶建立及管理網路。如需建立網路的詳細資訊、請參閱 link:sewebiug_define_network_configurations.html["定義具有子網路的網路組態"]。

.步驟
. 按一下「 * 建立租戶 * 」。
. 新增名稱和程式碼。代表租戶的程式碼應在 NetApp 服務引擎執行個體中是唯一的、並由大小寫較低的字元組成。
. 按一下「 * 建立 * 」。



NOTE: 您只能修改現有租戶的名稱和說明。此外、您無法刪除具有子租戶或與其相關聯之儲存元件的租戶。



== 子租戶

如果您是合作夥伴管理員或租戶管理員、則可以檢視及管理子租戶。



=== 建立子租戶

如果您是合作夥伴管理員或租戶管理員、可以從 * 管理 * > * 子租戶 * 建立、修改及刪除子租戶。您也可以為每個子租戶建立及管理網路。

如需建立網路的詳細資訊、請參閱 link:sewebiug_define_network_configurations.html["定義具有子網路的網路組態"]。

.步驟
. 按一下「 * 建立子租戶 * 」。
. 新增名稱和程式碼。代表子租戶的程式碼應在 NetApp 服務引擎執行個體中是唯一的、並由大小寫較低的字元組成。
. 按一下「 * 建立 * 」。



NOTE: 您只能修改現有子租戶的名稱。此外、您無法刪除具有相關儲存元件的子租戶。
