---
sidebar: sidebar 
permalink: sewebiug_managing_gcp_cvs.html 
keywords: netapp, keystone, managing CVS for GCP, gcp, Google Cloud Volume, CVS, Cloud Volumes Service 
summary: 在 Google Cloud Platform 上管理雲端 Volume 訂閱 
---
= 針對 Cloud Volumes Service GCP 管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
針對 Google Cloud Platform （ GCP ）訂閱 Cloud Volumes Service 的內容與租戶下的特定子租戶相關聯。子租戶訂閱單一 Google Cloud 服務。您可以為租戶和租戶建立及管理雲端服務（ Google Cloud 執行個體）、並根據租戶租賃在 Google Cloud 上配置儲存設備。租戶和子租戶的實體帳戶應先設定、才能透過 NetApp Service Engine 管理 Google Cloud 執行個體。 Cloud Volumes Service如需 Cloud Volumes Service 有關 GCP 上的資訊、請參閱 https://docs.netapp.com/us-en/occm/concept_cvs_gcp.html["深入瞭 Cloud Volumes Service 解適用於 Google Cloud 的功能"]。


NOTE: 租戶和子租戶的不二帳戶應已設定為 GCP 。 Cloud Volumes Service如需服務帳戶詳細資料、請聯絡支援部門。您需要客戶管理員存取權限才能管理 Google Cloud Volumes 。



== 在 GCP 上管理雲端服務

您可以從左導覽窗格的 * 雲端服務 * 功能表、在 Google Cloud 上管理雲端服務。「雲端服務」頁面會顯示所選租戶所有子租戶的所有雲端服務。您可以在此頁面檢視、修改及刪除雲端服務。您也可以依照下列步驟新增服務。

您必須確保：

* 子租戶已訂閱 Google Cloud 服務。
* 您有訂閱者服務帳戶的 Json 檔案、而且您知道與 Google Cloud 執行個體相關的 GCP 專案編號。
* 確保 Cloud Volumes Service 支援團隊已在 Cloud Manager 上設定適用於 GCP 的功能。如需詳細資訊、請參閱 https://docs.netapp.com/us-en/occm/task_setup_cvs_gcp.html["設定 Cloud Volumes Service 適用於 Google Cloud 的功能"]。


.步驟
. 從功能表中選取 * 雲端服務 * 。
. 按一下「 * 建立 * 」、然後按一下「 * Google Cloud * 」。
. 在 Google Cloud 的「 Create Cloud Service 」（建立雲端服務）頁面上、選取您要建立服務的子租戶、然後新增名稱和 GCP 專案編號。
. 在「 Google Cloud Credentials 」（ Google Cloud 認證）區段中、上傳含有服務帳戶認證的 Json 檔案。
. 如有需要、請將標記新增至服務。
. 按一下「 * 建立 * 」。建立之後、雲端服務頁面上的服務狀態會變更為「退費」。




== 在 GCP 上管理磁碟區

在 GCP 上管理雲端磁碟區之前、 Cloud Volumes Service 應先建立租戶的不確定帳戶、並訂閱雲端磁碟區。請聯絡支援部門、以確保這些步驟已完成。

您可以從左導覽窗格的 * 檔案服務 > GCP Volumes * 、在 GCP 上管理子租戶的磁碟區。GCP Volumes （ GCP 磁碟區）頁面列出在 GCP 上為所選子租戶和對應區域建立的現有雲端磁碟區。您可以在此頁面中檢視、修改及刪除現有的磁碟區。您也可以依照下列步驟來配置新的雲端磁碟區。

.步驟
. 從功能表中選取 * 檔案服務 > GCP Volumes * 。
. 按一下「 * 建立 * 」。隨即顯示 Create GCP Volume （建立 GCP Volume ）頁面。
. 選取您要為其建立 Volume 的子租戶。
. 選取地區和網路。此清單會根據 Cloud Volumes Service GCP 子租戶的不二帳戶進行篩選。
. 新增磁碟區名稱。
. 選取適當的服務層級。
. 輸入磁碟區的檔案路徑做為建立權杖。
. 指派磁碟區配額（以位元組為單位）。
. 如有需要、請新增磁碟區的標記。
. 按一下「 * 建立 * 」。建立後、 GCP Volumes （ GCP 磁碟區）頁面上的 Volume （磁碟區）狀態會變更為「 Cuceated （已退庫）」。


觀看下列影片、瞭解如何透過 Cloud Volumes Service 下列功能在 GCP 上建立 Volume ：

video::Crq5a1zi1Vg[youtube,width=750,height=400]