---
sidebar: sidebar 
permalink: sewebiug_back_up_file_shares_and_disks.html 
keywords: netapp, keystone, backup, create, modify, delete, restore 
summary: 建立、修改及刪除備份或從備份還原 
---
= 備份檔案共用和磁碟
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以檢視及管理環境中所建立之磁碟區（檔案共用區和磁碟）的 Snapshot （備份或還原點）、以遠端維護多個主要檔案共用和磁碟複本。

不同區域的複寫檔案共用和磁碟會儲存在每個叢集上的專用備份儲存 VM （儲存虛擬機器、也稱為 SVM ）上。可在 ONTAP 不同區域的兩個獨立的叢集之間執行備份。NetApp 服務引擎支援的標準備份原則包括：

* 特別的
* 每日
* 每週
* 每月


如果您的磁碟區未遵循 NetApp 服務引擎支援的標準備份原則、您可以 link:https://docs.netapp.com/us-en/keystone/sewebiug_raise_a_service_request.html["提出服務要求"] 解決此問題的 * 非標準磁碟區 * 類別。


NOTE: 可隨時手動透過 GUI 或使用 API 執行 Adhoc （非排程）備份。

您可以在「 * 備份 * 」頁面上檢視為檔案共用和磁碟所建立的 Snapshot 清單。備份會根據選取的租戶顯示。



== 建立備份物件

您可以在需要時定義備份原則、為磁碟區建立 Snapshot link:https://docs.netapp.com/us-en/keystone/sewebiug_create_a_new_file_share.html["建立檔案共用區"] 或 link:https://docs.netapp.com/us-en/keystone/sewebiug_create_a_new_disk.html["建立磁碟"]。

.步驟
. 啟用 * 備份原則 * 。
. 指定備份區域、以及每月、每日、每週及 / 或每月進行的備份數量。
. 按一下「 * 建立 * 」。



NOTE: 您也可以編輯現有檔案共用區或磁碟的備份原則、來建立或排程備份。



== 修改備份物件

對於檔案共用區或磁碟的選定備份物件、您可以停用備份、或將備份物件從其來源分離、使其成為孤立備份。此作業會中斷 SnapMirror 與來源的關係。您也可以修改每月、每日、每週和 / 或每月進行的備份數量。

.步驟
. 在清單中找出備份、然後按一下該物件列末端的編輯圖示。
. 視需要變更備份來源和每種備份類型的數量。您可以將備份來源變更為 * 無（孤立） * 、藉此中斷 SnapMirror 與來源磁碟區的關係。即使刪除來源磁碟區、備份仍會保留為孤立備份、以供還原。備份物件的狀態會變更、來源磁碟區的狀態（孤立或刪除）會附加到同一個清單上的來源磁碟區名稱。如需物件狀態的相關資訊、請參閱 link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#Object-states["請按這裡"]
. 按一下「 * 完成 * 」。Snapshot 即會修改。如果您中斷了與來源的 SnapMirror 關係、也就是孤立備份物件、則「 * 備份 * 」索引標籤中的來源名稱會顯示為「已刪除」。



NOTE: 您也可以停用磁碟區的 * 備份原則 * 、中斷 SnapMirror 與來源磁碟區的關係。



== 刪除備份物件

刪除未使用的備份磁碟區以增加儲存空間。

.步驟
. 在清單中找出備份、然後按一下該物件列末端的刪除圖示。
. 在「 * 確認刪除 * 」對話方塊中、輸入備份名稱（來源 Volume 名稱）以確認您要刪除備份物件。
. 按一下「 * 確認 * 」。



NOTE: 刪除備份時、會刪除備份的所有恢復點。此外、即使您刪除主要檔案共用區或磁碟、備份仍會保留為孤立備份、並保留所有還原點。若要刪除刪除來源的備份磁碟區和還原點、您應該從 * 備份 * 索引標籤中明確刪除備份物件。



== 備份還原

您可以 link:https://docs.netapp.com/us-en/keystone/sewebiug_raise_a_service_request.html["提出服務要求"] 從特定的還原點還原檔案共用區或磁碟。

.步驟
. 從左側導覽窗格中選取 * support* 、然後選取 * Service Requests * 。
. 按一下「 * 新服務要求 * 」。
. 選擇 * 備份還原 * 作為服務要求的類別。
. 請指定其他詳細資料並繼續。

