---
sidebar: sidebar 
permalink: sewebiug_create_file_share_from_snapshot.html 
keywords: netapp, keystone, create, file share, Snapshot 
summary: 從 Snapshot 建立檔案共用區 
---
= 從 Snapshot 建立檔案共用區
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以從現有的 Snapshot 建立新的檔案共用區。從 Snapshot 複製的新檔案共用具有與建立 Snapshot 的檔案共用相同的屬性。

.步驟
. 從左側導覽窗格中選取 * 檔案服務 * 、然後選取 * 共享 * 。
. 按一下「 * 建立共用 * 」、然後選取「 * 從 Snapshot 複製 * 」。「 * 選取共用 * 」畫面會顯示租戶的所有檔案共用。您可以依區域、區域和子租戶篩選檔案共用。您可以選取任何處於作業狀態的檔案共用區。
. 選取您要的檔案共用旁的核取方塊、然後按一下 * 下一步 * 。「選擇 Snapshot 」畫面會顯示檔案共用的所有 Snapshot 。
+

NOTE: 對於所選的檔案共用、如果 SnapCenter 您在 NetApp 服務引擎以外的環境中建立了一些 Snapshot 快照、您可以找到這些 Snapshot 已匯入並列出供您選擇。您可以選取這些匯入的 Snapshot 、然後從它們複製新的檔案共用。

+
您可以搜尋特定的 Snapshot 或選取排程類型來篩選 Snapshot 。

. 選中要從中克隆的 Snapshot 旁邊的複選框，然後單擊 * Next* （下一步 * ）。新的檔案共用區會繼承所選 Snapshot 的內容。
. 新增 * 名稱 * 和 * 共用路徑 * 。更新其他設定、例如指派 * 服務層級 * 、然後按一下 * 建立 * 。


.完成後
* 僅限 CIFS 類型共用：若要讓共用區可供主機名稱使用、您的網域管理員應使用 CIFS 伺服器名稱和 IP 位址來更新 DNS 記錄。否則、只能透過 IP 位址存取共用區。例如：
+
** 更新 DNS 記錄後、請使用主機名稱或 IP 來存取共用區：例如 file://hostname/share["\hostname\share"^] 或 file://IP/share["\ip\share"^]
** 如果沒有更新 DNS 記錄、您應該使用 IP 位址來存取共用區、例如 file://IP/share["\ip\share"^]


* * Create Share* 以非同步工作的形式執行。您可以：
+
** 檢查工作清單中的工作狀態。如需追蹤工作的相關資訊、請參閱 link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["請按這裡"]。
** 工作完成後、請檢查「 * 共享區 * 」清單中的共享區狀態。



