---
sidebar: sidebar 
permalink: sewebiug_managing_subscriptions.html 
keywords: netapp, keystone, managing, subscriptions, 
summary: Keystone 管理訂閱 
---
= 管理訂閱
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
管理訂閱內容包括指派服務層級給 NetApp Keystone 您的《 Flex訂購 》（ Flex 訂購）和租戶訂閱服務、或是使用 NetApp 服務引擎介面、將容量分配及變更至服務層級。

由服務供應商 / 合作夥伴與 NetApp 及租戶訂閱之間的關係所代表的 Flex 訂閱、代表服務供應商與其租戶和租戶（終端客戶）之間的關係。當 NetApp 管理員或 GSSC 為合作夥伴和租戶建立 Flex 訂閱服務時、即表示儲存設備配置已完成。不過、除非建立服務層級、且已完成對應的容量配置、否則子租戶或終端客戶將無法使用儲存設備。合作夥伴管理員可以管理彈性訂閱和租戶訂閱的儲存設備。租戶管理員只能檢視租戶訂閱詳細資料及其租賃服務。



== 管理彈性訂閱（基礎概念訂閱）

如果您是合作夥伴管理員、可以從 * 訂購 * > * 基礎概念訂閱 * 檢視及管理您的 Flex 訂閱服務。* Keystone 訂閱 * 代表 NetApp 管理員為合作夥伴所建立的 Flex 訂閱服務。合作夥伴管理員可檢視其 Flex 訂閱服務、並建立服務要求以：

* 增加訂閱容量
* 新增服務至訂閱（指派服務層級和容量）


支援團隊會收到並處理服務要求。

您也可以在個別的索引標籤中檢視及管理您訂閱的資料保護和進階保護服務。



=== 增加訂閱容量

您可以增加任何已訂閱服務層級的已認可容量、以符合成長需求。

.步驟
. 從下拉式功能表中選取您要增加容量的訂閱。
. 按一下 * 「增加容量」 * 以取得所需的服務層級。
. 指定所需的容量（以 TiB 為單位）。
. 按一下「 * 確認 * 」。




=== 新增服務至訂閱

您可以將服務新增至訂閱。新增服務包括指派服務層級給您的訂閱、以及指定相同服務層級的容量。

訂閱可能只有每個效能層級的其中一個、例如、如果您的訂閱已包含極致版和標準版服務、您可以新增優質或區塊服務。

.步驟
. 從下拉式功能表中選取您要增加容量的訂閱。
. 按一下「 * 新增服務 * 」。
. 從下拉式功能表中選取您要新增的訂閱服務、然後新增您要提交至服務層級的容量（以 TiB 為單位）。
. 按一下「 * 確認 * 」。



NOTE: 如果您訂閱極致分層或優質分層、您可以編輯任何現有訂閱的效能等級、並選擇啟用分層的效能等級。您也可以選擇從啟用分層的效能層級移至非分層效能層級。



== 管理租戶訂閱

如果您是合作夥伴管理員、可以從 * 訂購 * > * 租戶訂閱 * 建立、檢視及更新租戶訂閱。如果您是租戶管理員、則只能檢視訂閱內容。



=== 建立租戶訂閱

您可以為租戶建立新的訂閱。

.步驟
. 按一下「 * 新訂閱 * 」。
. 指定地區、區域、訂閱期限、費率計畫及其他詳細資料。租戶訂閱會根據選取的區域指派給 Keystone 訂閱。這是因為每個 Keystone 訂閱都繫結至一個區域。
+

NOTE: 您無法建立重疊的訂閱。開始日期應至少為隔天、因為訂閱的開始日期應早於指定的開始日期一天。此外、自目前日期起、不得超過 30 天。

. 按一下「 * 建立 * 」。


您無法刪除任何訂閱。您只能編輯現有的租戶訂閱、新增服務層級、增加服務層級的已提交容量、以及新增訂閱標記。
