---
sidebar: sidebar 
permalink: sewebiug_partner_service_provider.html 
keywords: netapp, service, engine, web, portal, partner, service provider 
summary: NetApp 服務引擎合作夥伴、服務供應商功能 
---
= 服務供應商與客戶的角色與營運
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
根據您的服務供應商或合作夥伴（可互換使用）或客戶或租戶（可互換使用）管理員角色、 NetApp 服務引擎入口網站上的檢視和功能將會由您決定。



== 您可以做為服務供應商管理員執行的活動

身為多租戶環境中的服務供應商管理員、您可以透過 NetApp Service Engine Web UI 執行資源配置、報告、帳單及管理擁有自己訂閱的客戶。您可以執行下列功能：

* 以 Keystone 訂閱服務的一部分檢視已訂閱和已佈建的儲存設備。
+

NOTE: 作為服務項目、您可以向客戶銷售比向 NetApp 購買更多容量（超額訂閱）。租戶訂閱可能會超過目前的 Keystone 訂閱期間、但在訂閱建立時間和儀表板 / 報告中會顯示警告。

* 建立、檢視、修改及刪除租戶、子租戶、 和使用者。
* 檢視您訂閱的區域和區域。
* 在 Keystone 訂閱服務中管理及裝載多個租戶：建立及管理租戶訂閱、並檢視您自己的 Keystone 訂閱詳細資料。
+

NOTE: 租戶訂閱可以根據對應的區域和 Keystone Keystone 訂閱來建立。它們是根據 Keystone 訂閱的訂閱容量所提供的服務層級所建立。

* 建立檔案伺服器或區塊儲存區、並初始化區塊、檔案和物件儲存區、因為您知道為租戶配置每種儲存類型的網路需求。
* 您也可以為租戶建立及管理子網路、
* 檢視作為 Keystone 訂閱一部分所建立的檔案共用、磁碟和貯體。也可建立及管理物件儲存群組和使用者。
* 根據您的 Keystone 訂閱、租戶訂閱和所有租戶的使用情況、建立報告以供使用、以便在個別的計費和評分系統中使用。
* 檢視所有租戶與客戶的帳單與報告、以及僅訂閱或已配置儲存設備的帳單與報告。
* 在您自己的（合作夥伴 / 服務供應商）服務要求工具（與 OpsRamp/GSSC 整合）中、檢視及管理客戶提出的服務要求。




== 您可以做為客戶 / 租戶管理員執行的活動

身為租戶管理員、您有權檢視自己租戶的訂閱詳細資料、並為您的子租戶執行管理工作。您可以執行下列動作：

* 檢視租戶訂閱服務中已訂閱及已配置的儲存設備。
* 管理及編輯租戶以供租戶使用。
* 檢視您的區域、區域、子租戶和子網路。
* 檢視服務供應商所建立的檔案伺服器。
* 建立檔案共用區、磁碟區和儲存區、然後指派服務層級給它們。
* 從*「報告」>「容量使用率」*檢視租戶和子租戶的報告、以僅檢視訂閱或為租戶和子租戶配置之儲存設備的使用量資料。
* 從*「報告」>「效能」*檢視租戶與租戶的報告、以檢視每項訂閱服務與附加服務（資料保護與進階保護）的租約效能與服務法規遵循。
+

NOTE: 如需額外訂閱、您可以使用服務要求工具。


