---
sidebar: sidebar 
permalink: sewebiug_managing_azure_netapp_accounts.html 
keywords: netapp, keystone, managing, azure, accounts, 
summary: 管理 Azure NetApp 帳戶 
---
= 管理 Azure NetApp 帳戶
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
本節說明如何管理 Azure NetApp 帳戶：


NOTE: 管理 Azure NetApp 帳戶需要客戶管理存取權。

在本節中：

* 檢視 azure NetApp 帳戶清單
* 新增 Azure NetApp 帳戶
* 修改 Azure NetApp 帳戶詳細資料
* 刪除 Azure NetApp 帳戶




== 檢視 Azure NetApp 帳戶清單

Azure NetApp 帳戶清單會顯示登入使用者可存取之租約中所有 Azure NetApp 帳戶的清單。若要檢視清單、請從功能表中選取 * 管理 > Azure NetApp Accounts * 。

清單會顯示每個 Azure NetApp 帳戶的簡單資訊。每個 Azure NetApp 帳戶旁的行動圖示可讓您修改或刪除 Azure NetApp 帳戶。



== 新增 Azure NetApp 帳戶

本節說明如何新增 Azure NetApp 帳戶。

.開始之前
您需要：

* Azure NetApp 帳戶所屬的子租戶
* ANF 執行個體
* Azure 位置（地區）
* Azure 資源群組
* 帳戶名稱


.步驟
. 從功能表中選取 * 管理 > Azure NetApp Accounts * 。
. 按一下「 * 建立 * 」。
. 在「 Create Azure NetApp Account （建立 Azure NetApp 帳戶）」對話方塊中、指定子租戶、 Azure 位置（地區）、 Azure 資源群組、以及 Azure NetApp 帳戶的名稱。
. 如有需要、請將標記新增至帳戶。
. 按一下「 * 建立 * 」。成功建立帳戶後、帳戶狀態將會成功（可在 Azure NetApp 帳戶清單中檢視）。




== 修改 Azure NetApp 帳戶標記

使用此方法修改 Azure NetApp 帳戶的相關標記。

.步驟
. 從功能表中選取 * 管理 > Azure NetApp Accounts * 。
. 在清單中找到 Azure NetApp 帳戶、然後按一下編輯圖示。
. 在「管理 Azure NetApp 帳戶」對話方塊中、視需要新增、移除或編輯標記。
. 按一下 * 更新 * 。




== 刪除 Azure NetApp 帳戶

使用此方法刪除 Azure NetApp 帳戶。

.步驟
. 從功能表中選取 * 管理 > Azure NetApp Accounts * 。
. 在清單中找到 Azure NetApp 帳戶、然後按一下刪除圖示。
. 在「確認刪除」對話方塊中、輸入要刪除的 Azure NetApp 帳戶名稱。
. 按一下「 * 確認 * 」。

