---
sidebar: sidebar 
permalink: sewebiug_define_network_configurations.html 
keywords: netapp, keystone, subnet, subtenant, network, tenant network, IPspace, VLAN, port 
summary: 建立及刪除子網路 
---
= 定義租戶和子租戶的網路組態
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
服務供應商或合作夥伴管理員可以根據租戶的訂閱區域來定義網路組態、並將 VLAN 指派給每個網路組態。他們也可以建立子網路、讓每個 VLAN 都屬於同一個區域和租戶、並將其指派給該租戶下的子租戶。

需要預先設定的租戶網路才能建立子網路。當子租戶或終端客戶配置檔案伺服器或區塊存放區時、必須使用子網路。檔案和區塊儲存 VM 歸 NetApp Service Engine 的子租戶所有、而 ONTAP 它們則歸 NetApp 的 IPspaces 所有。當您在子租戶層級定義網路邊界時、 NetApp Service Engine 中的子租戶會對應 ONTAP 至該區域的單一支援區 IPspace 。如此可避免風險、並確保兩個不同的子租戶不會選擇相同的 VLAN ID 、最終會在相同的 IPspace 中結束。

* 每個區域中可以建立多個子網路。對於租戶所在的每個區域、都有一個已分配的 VLAN 清單。對於所有可用的 VLAN 、都可以建立對應的子網路。子網路與 VLAN 之間有一對一對應關係。不過、子網路和區域之間有許多對應關係。
* 一個租戶可以有多個子網路、一個區域下的每個可用 VLAN 各有一個子網路。它們會顯示在每個區域的單一網路組態下。
* 每個子網路只能有一個 VLAN 。每個網路組態都會顯示可用的 VLAN 清單。
* 只能為子租戶建立一個區域和 VLAN 組合子網路。



NOTE: 租戶管理員只能檢視其租戶的網路組態及其子租戶的子網路。



== 定義租戶的網路組態

身為合作夥伴管理員、您可以為每個租戶建立網路組態。可設定且唯一的 VLAN 集區可根據租戶需求分配給每個租戶。刪除租戶時、會將與其相關的 VLAN 釋出回租戶 VLAN 集區。

.開始之前
* 確保已建立租戶
* 您應該知道區域、VLAN、子網路CIDR和連接埠置換組態


.步驟
. 從 * 管理 * > * 租戶 * 中、選取所需租戶。
. 按一下網路圖示。「網路」畫面會顯示租戶的網路組態清單。
. 按一下「 * 建立網路 * 」。如果適用、請指定區域、 VLAN 和連接埠置換。如果已定義連接埠置換、請從下拉式清單中選取指派的連接埠。對於該租戶的所有網路連線、會使用此連接埠、而非預設連接埠。
+

NOTE: 連接埠置換是由支援團隊在區域組態期間設定的。如果未指定連接埠置換、則網路會使用預設連接埠、並為該租戶建立新的VLAN。

. 按一下「 * 建立 * 」。「網路」畫面會列出租戶的新網路組態。


如果已建立區域的網路組態、您只能將新的 VLAN 指派給網路組態。按一下「 * + * 」圖示、然後新增 VLAN 和連接埠置換詳細資料。按一下 * 更新 * 。



== 為子租戶建立子網路

身為合作夥伴管理員、您可以從 * 網路 * > * 子網路 * 為子網路租戶建立子網路。子網路定義包含 ONTAP 在《 Escale （環路）」中實作的 VLAN ID 、 CIDR 位址範圍和路由規格。子網路會對齊租戶和區域內的 VLAN 。您無法為區域建立具有相同 VLAN 的兩個子網路。

.開始之前
* 租戶的 VLAN 和區域組態應該已經完成
* 您應該瞭解要建立子網路的需求


.步驟
. 選取所需的租戶。您為其建立子網路的子租戶應屬於此租戶。
. 按一下 * 網路 * > * 子網路 * 。您可以在「 * 子網路 * 」頁面上檢視為子租戶建立的子網路清單。
. 按一下「 * 建立子網路 * 」。
. 指定子租戶、區域、子網路名稱、 VLAN 和子網路 CIDR 。您也可以新增航線規格和標記。
+

NOTE: 在路由規格中、 * 目的地 * 應為唯一且屬於所述 VLAN 的一部分、而多個路由的 * 指標 * 值可以相同。

. 按一下「 * 建立 * 」。



NOTE: 您無法編輯或刪除子網路。您只能編輯與其相關的標記。
