---
sidebar: sidebar 
permalink: sewebiug_back_up_file_shares_and_disks.html 
keywords: netapp, keystone, backup, create, modify, delete, restore 
summary: 建立、修改及刪除備份或從備份還原 
---
= 備份檔案共用和磁碟
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以定義備份原則、在環境中建立磁碟區（檔案共用區和磁碟）的備份、並從遠端維護多個主要磁碟區複本。


NOTE: 當您建立或編輯磁碟區的備份原則時、系統會自動建立備份。您無法從NetApp服務引擎介面建立備份。您可以使用備份API來建立及管理磁碟區的備份。

如需相關資訊、請參閱 link:seapiref_backups_apis.html["備份API"]

備份來源磁碟區是透過啟用 Keystone 訂閱服務的 NetApp SnapMirror 技術來啟用。如需相關資訊、請參閱 link:index.html#flex-subscription["請按這裡"]。

當您建立或編輯Volume時、會定義其備份排程。備份會依照預定的時間間隔進行、並儲存在目的地系統中。為了讓備份正常運作、SnapMirror關係應與目的地環境建立。不同區域的複寫檔案共用和磁碟會儲存在每個叢集上的專用備份儲存 VM （儲存虛擬機器、也稱為 SVM ）上。可在 ONTAP 不同區域的兩個獨立的叢集之間執行備份。

NetApp 服務引擎支援的標準備份原則包括：

* 特別的
* 每日
* 每週
* 每月


對於在後端建立的備份、您的磁碟區應處於「運作」狀態。如需物件狀態的詳細資訊、請參閱運作（如需備份的來源物件）。 link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["請按這裡"]。

如果您的磁碟區未遵循 NetApp 服務引擎支援的標準備份原則、您可以 link:sewebiug_raise_a_service_request.html["提出服務要求"] 解決此問題的 * 非標準磁碟區 * 類別。

您可以在*備份*頁面上檢視為檔案共用和磁碟建立的備份清單。備份會根據選取的租戶顯示。



== 編輯備份原則或排程

當您建立或編輯檔案共用和磁碟時、可以定義其備份原則。備份會根據您指定的原則在後端進行。如需相關資訊、請參閱： link:sewebiug_create_a_new_file_share.html["建立檔案共用區"] 或 link:sewebiug_create_a_new_disk.html["建立磁碟"]。

.步驟
. 啟用 * 備份原則 * 。
. 指定備份區域、以及每月、每日、每週及 / 或每月進行的備份數量。
. 按一下「 * 建立 * 」。



NOTE: 您也可以編輯現有檔案共用區或磁碟的備份原則、來排程備份。



== 修改或中斷備份來源的連線

對於檔案共用區或磁碟的選定備份物件、您可以停用備份、或將備份物件從其來源分離、使其成為孤立備份。此作業會中斷 SnapMirror 與來源的關係。您也可以修改每月、每日、每週和 / 或每月進行的備份數量。

.步驟
. 在左側導覽窗格中、按一下*備份*。您可以查看為環境中的所有物件所建立的備份清單。
. 在清單中找到備份（依磁碟區名稱搜尋）、然後按一下列結尾的編輯圖示。
. 視需要變更備份來源和每種備份類型的數量。您可以將備份來源變更為 * 無（孤立） * 、藉此中斷 SnapMirror 與來源磁碟區的關係。即使刪除來源磁碟區、備份仍會保留為孤立備份、以供還原。備份物件的狀態會變更、來源磁碟區的狀態（孤立或刪除）會附加到同一個清單上的來源磁碟區名稱。如需物件狀態的相關資訊、請參閱 link:sewebiug_netapp_service_engine_web_interface_overview.html#Object-states["請按這裡"]
. 按一下「 * 完成 * 」。快照已修改。如果您中斷了與來源的 SnapMirror 關係、也就是孤立備份物件、則「 * 備份 * 」索引標籤中的來源名稱會顯示為「已刪除」。



NOTE: 您也可以從Create Share/Edit Share（建立共用/編輯共用）和Create Disk/Edit Disk（建立磁碟/編輯磁碟）畫面停用磁碟區的* Backup Policy*、藉此中斷SnapMirror與來源磁碟區的關係。



== 要求備份與還原支援

您可以 link:sewebiug_raise_a_service_request.html["提出服務要求"] 從特定的還原點還原檔案共用區或磁碟。

.步驟
. 從左側導覽窗格中選取 * support* 、然後選取 * Service Requests * 。
. 按一下「 * 新服務要求 * 」。
. 選擇 * 備份還原 * 作為服務要求的類別。
. 請指定其他詳細資料並繼續。




== 移除備份物件

刪除未使用的備份磁碟區會增加儲存空間。若要刪除已刪除來源的備份磁碟區和還原點、您應該使用備份API。


NOTE: 刪除備份時、會刪除備份的所有恢復點。此外、即使您刪除主要檔案共用區或磁碟、備份仍會保留為孤立備份、並保留所有還原點。
