---
sidebar: sidebar 
permalink: sewebiug_managing_subscriptions.html 
keywords: netapp, keystone, managing, subscriptions, 
summary: Keystone 管理訂閱 
---
= 管理訂閱
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
管理訂閱內容包括指派服務層級給 NetApp Keystone 您的《 Flex訂購 》（ Flex 訂購）和租戶訂閱服務、或是使用 NetApp 服務引擎介面、將容量分配及變更至服務層級。

由服務供應商 / 合作夥伴與 NetApp 及租戶訂閱之間的關係所代表的 Flex 訂閱、代表服務供應商與其租戶和租戶（終端客戶）之間的關係。當 NetApp 管理員或 GSSC 為合作夥伴和租戶建立 Flex 訂閱服務時、即表示儲存設備配置已完成。不過、除非建立服務層級、且已完成對應的容量配置、否則子租戶或終端客戶將無法使用儲存設備。合作夥伴管理員可以管理彈性訂閱和租戶訂閱的儲存設備。租戶管理員只能檢視租戶訂閱詳細資料及其租賃服務。



== 管理彈性訂閱（基礎概念訂閱）

如果您是合作夥伴管理員、可以從 * 訂購 * > * 基礎概念訂閱 * 檢視及管理您的 Flex 訂閱服務。* Keystone 訂閱 * 代表 NetApp 管理員為合作夥伴所建立的 Flex 訂閱服務。合作夥伴管理員可檢視其 Flex 訂閱服務、並建立服務要求以：

* 增加訂閱容量
* 新增服務至訂閱（指派服務層級和容量）


支援團隊會收到並處理服務要求。

您也可以在個別的索引標籤中檢視及管理您訂閱的資料保護和進階保護服務。如需相關資訊、請參閱 link:index.html#flex-subscription["進階資料保護與資料保護"]。



=== 增加訂閱容量

您可以增加任何已訂閱服務層級的已認可容量、以符合成長需求。

.步驟
. 從下拉式功能表中選取您要增加容量的訂閱。
. 按一下 * 「增加容量」 * 以取得所需的服務層級。
. 指定所需的容量（以 TiB 為單位）。
. 按一下「*確認*」。您會返回「管理基礎概念訂閱」頁面。
. 按一下*提交變更*。已針對GSSC建立服務要求、以增加容量。您可以依訊息中顯示的SR號碼來檢視及追蹤服務要求的進度。如需追蹤的資訊、請參閱 link:sewebiug_track_a_service_request.html["追蹤服務要求"]。




=== 新增服務至訂閱

您可以將服務新增至訂閱。新增服務包括指派服務層級給您的訂閱、以及指定相同服務層級的容量。

每個訂閱都可以擁有每個服務層級的其中一個。例如、如果您的訂閱已包含極致版和標準版服務、您可以新增優質或區塊服務。

.步驟
. 從下拉式功能表中選取您要新增至訂閱的服務層級。
. 按一下「 * 新增服務 * 」。
. 從下拉式功能表中選取您要訂閱的服務層級、例如「極致分層」、然後新增您要承諾服務層級的容量（以TiB為單位）。
. 按一下「 * 確認 * 」。您將返回「管理基礎概念訂閱」頁面。
. 按一下*提交變更*。已針對GSSC建立服務要求、將服務層級指派給您的訂閱。您可以依訊息中顯示的SR號碼來檢視及追蹤服務要求的進度。


如需追蹤的資訊、請參閱 link:sewebiug_track_a_service_request.html["追蹤服務要求"]。



== 管理租戶訂閱

如果您是合作夥伴管理員、可以從 * 訂購 * > * 租戶訂閱 * 建立、檢視及更新租戶訂閱。如果您是租戶管理員、則只能檢視訂閱內容。



=== 建立及編輯租戶訂閱

您可以為租戶建立新的訂閱。

.步驟
. 按一下「 * 新訂閱 * 」。
. 指定地區、區域、訂閱期限、費率計畫及其他詳細資料。租戶訂閱會根據選取的區域指派給 Keystone 訂閱。這是因為每個 Keystone 訂閱都繫結至一個區域。
+

NOTE: 您無法建立重疊的訂閱。開始日期應至少為隔天、因為訂閱的開始日期應早於指定的開始日期一天。此外、自目前日期起、不得超過 30 天。

. 按一下「 * 建立 * 」。


您無法刪除任何訂閱。您只能編輯現有的租戶訂閱、新增服務層級、增加服務層級的已提交容量、以及新增訂閱標記。

如果您是合作夥伴管理員、可以編輯租戶訂閱。您可以新增新的服務層級至訂閱、並編輯已新增服務層級的容量。若要新增服務層級、請遵循下列步驟：

.步驟
. 按一下「+」圖示、選取您要編輯的訂閱。
. 在「*新增服務層級至訂閱*」頁面上、選取新的服務層級並新增所需的容量。如果已新增服務層級、您就無法新增或刪除它。
. 按一下 * 更新 * 。


您也可以按一下訂閱的標記圖示來新增標記。

若要將訂閱的容量編輯為已指派給訂閱的服務層級、請遵循下列步驟：

.步驟
. 按一下「v」圖示、然後展開您要編輯的訂閱。隨即顯示該訂閱中的服務層級。
. 按一下個別的編輯筆圖示、選取您要編輯的服務層級。
. 透過增加或減少Tibs的容量來變更費率計畫。
. 按一下 * 更新 * 。

